//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_CONTROL
    {
        public decimal ACC_AUTO_KEY { get; set; }
        public Nullable<decimal> MXS_AUTO_KEY { get; set; }
        public Nullable<decimal> MXS_COMPLETE { get; set; }
        public Nullable<decimal> CMP_DEFAULT { get; set; }
        public Nullable<decimal> HOURS_DEFAULT { get; set; }
        public Nullable<decimal> CYCLES_DEFAULT { get; set; }
        public Nullable<decimal> DAYS_DEFAULT { get; set; }
        public string LOGICAL_PART { get; set; }
        public Nullable<decimal> MXS_WO { get; set; }
        public Nullable<decimal> WEEKLY_FLIGHT_HOURS { get; set; }
        public Nullable<decimal> WEEKLY_FLIGHT_CYCLES { get; set; }
        public Nullable<decimal> DAY_TOLERANCE { get; set; }
        public string TRACK_CHANGES { get; set; }
        public Nullable<decimal> POL_DEFER { get; set; }
        public Nullable<decimal> MXS_CANCEL { get; set; }
        public Nullable<decimal> MXS_WP_CANCEL { get; set; }
        public Nullable<decimal> WTM_AUTO_KEY { get; set; }
        public string AUTO_SEQ { get; set; }
        public string CAMP_HOST { get; set; }
        public string CAMP_PORT { get; set; }
        public string CAMP_PATH { get; set; }
        public string CAMP_USE_SSL { get; set; }
        public string CAMP_SSL_FILE { get; set; }
        public string CAMP_2WAY { get; set; }
        public string CAMP_SHOW_SUB_TASKS { get; set; }
        public string CAMP_REQ_TEMPLATE { get; set; }
        public string CAMP_REQ_PARENT_TASK { get; set; }
        public string AUTO_PUB { get; set; }
        public string CAMP_USE_PROXY { get; set; }
        public string CAMP_PROXY_ADDRESS { get; set; }
        public Nullable<decimal> CAMP_PROXY_PORT { get; set; }
        public string PROMPT_SIGNOFF { get; set; }
        public string REQ_TEMPLATE_FOR_SCHED_MX { get; set; }
        public string MOST_RECENT_PUBS_FOR_FINDINGS { get; set; }
        public string PRINT_JC { get; set; }
        public string PREV_MOVE_TASKS_ISSUED_PARTS { get; set; }
        public string DEF_QA_REQUIRED { get; set; }
        public string DEF_USE_MIN_REC { get; set; }
        public string AVTRAK_DEV { get; set; }
        public string CAMP_DEV { get; set; }
        public Nullable<decimal> WTM_CAMP { get; set; }
        public string DEFER_POLICY_WARNING { get; set; }
        public string REFRESH_PUBLICATIONS { get; set; }
        public string APPLY_DEF_TEMPLATE_TASKS { get; set; }
        public string JC_STYLE { get; set; }
        public string NETJETS_DEV { get; set; }
        public string UNRES_PT_STYLE { get; set; }
        public string USE_WRKREQ_FOR_LOGBK { get; set; }
        public string DEF_MEC_REQ { get; set; }
        public string USE_PURCHASE_CONTROL { get; set; }
        public string DEF_PURCHASE_CONTROL { get; set; }
        public string UPDATE_JC_BG_ORIG_TASK_SEQ { get; set; }
        public string NETJETS_TEMPLATES_ONLY { get; set; }
        public string QCNJ_WORK_ORDER_IMPORTER_URL { get; set; }
        public Nullable<decimal> WTM_NETJETS { get; set; }
        public string NETJETS_REQ_TEMPLATE { get; set; }
        public Nullable<decimal> WOS_CAMP_CLOSE { get; set; }
    
        public virtual COMPANy COMPANy { get; set; }
    }
}
