//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_STATUS_TYPE
    {
        public decimal AST_AUTO_KEY { get; set; }
        public string STATUS_TYPE { get; set; }
        public string STATUS_CODE { get; set; }
        public string STATUS_DESC { get; set; }
        public string SDF_AST_001 { get; set; }
        public string SDF_AST_002 { get; set; }
        public string SDF_AST_003 { get; set; }
        public string SDF_AST_004 { get; set; }
        public string SDF_AST_005 { get; set; }
        public string SDF_AST_006 { get; set; }
        public string SDF_AST_007 { get; set; }
        public string SDF_AST_008 { get; set; }
        public string SDF_AST_009 { get; set; }
        public string SDF_AST_010 { get; set; }
    }
}
