//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT
    {
        public AGENT()
        {
            this.COMPANY_AGENTS = new HashSet<COMPANY_AGENTS>();
            this.CQ_HEADER = new HashSet<CQ_HEADER>();
            this.INVC_DETAIL = new HashSet<INVC_DETAIL>();
            this.SO_HEADER = new HashSet<SO_HEADER>();
            this.SYS_USERS = new HashSet<SYS_USERS>();
        }
    
        public decimal AGN_AUTO_KEY { get; set; }
        public string AGENT_CODE { get; set; }
        public string AGENT_NAME { get; set; }
        public string CONVERTED { get; set; }
        public Nullable<decimal> AGENT_COMM { get; set; }
        public string SDF_AGN_001 { get; set; }
        public string SDF_AGN_002 { get; set; }
        public string SDF_AGN_003 { get; set; }
        public string SDF_AGN_004 { get; set; }
        public string SDF_AGN_005 { get; set; }
        public string SDF_AGN_006 { get; set; }
        public string SDF_AGN_007 { get; set; }
        public string SDF_AGN_008 { get; set; }
        public string SDF_AGN_009 { get; set; }
        public string SDF_AGN_010 { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public string HISTORICAL { get; set; }
    
        public virtual ICollection<COMPANY_AGENTS> COMPANY_AGENTS { get; set; }
        public virtual ICollection<CQ_HEADER> CQ_HEADER { get; set; }
        public virtual ICollection<INVC_DETAIL> INVC_DETAIL { get; set; }
        public virtual ICollection<SO_HEADER> SO_HEADER { get; set; }
        public virtual ICollection<SYS_USERS> SYS_USERS { get; set; }
    }
}
