//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALTERNATE_TYPE_CODES
    {
        public ALTERNATE_TYPE_CODES()
        {
            this.ALTERNATES_PARTS_MASTER = new HashSet<ALTERNATES_PARTS_MASTER>();
        }
    
        public decimal ATC_AUTO_KEY { get; set; }
        public string ALT_TYPE_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CANNOT_MODIFY { get; set; }
        public decimal SEQUENCE { get; set; }
        public string CONVERTED { get; set; }
        public string SDF_ATC_001 { get; set; }
        public string SDF_ATC_002 { get; set; }
        public string SDF_ATC_003 { get; set; }
        public string SDF_ATC_004 { get; set; }
        public string SDF_ATC_005 { get; set; }
        public string SDF_ATC_006 { get; set; }
        public string SDF_ATC_007 { get; set; }
        public string SDF_ATC_008 { get; set; }
        public string SDF_ATC_009 { get; set; }
        public string SDF_ATC_010 { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
    
        public virtual ICollection<ALTERNATES_PARTS_MASTER> ALTERNATES_PARTS_MASTER { get; set; }
    }
}
