//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALTERNATES_PARTS_MASTER
    {
        public decimal APM_AUTO_KEY { get; set; }
        public Nullable<decimal> PNM_AUTO_KEY { get; set; }
        public Nullable<decimal> ALT_PNM_AUTO_KEY { get; set; }
        public Nullable<decimal> ATC_AUTO_KEY { get; set; }
        public Nullable<decimal> SEQUENCE { get; set; }
        public string NOTES { get; set; }
        public string PRINT_FLAG { get; set; }
        public string CONVERTED { get; set; }
        public string IQ_VISIBLE { get; set; }
        public string SDF_APM_001 { get; set; }
        public string SDF_APM_002 { get; set; }
        public string SDF_APM_003 { get; set; }
        public string SDF_APM_004 { get; set; }
        public string SDF_APM_005 { get; set; }
        public string SDF_APM_006 { get; set; }
        public string SDF_APM_007 { get; set; }
        public string SDF_APM_008 { get; set; }
        public string SDF_APM_009 { get; set; }
        public string SDF_APM_010 { get; set; }
        public string DP_VISIBLE { get; set; }
        public string CUSTOMER_PN { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
    
        public virtual ALTERNATE_TYPE_CODES ALTERNATE_TYPE_CODES { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER1 { get; set; }
    }
}
