//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_ACCOUNT
    {
        public AP_ACCOUNT()
        {
            this.AP_DETAIL = new HashSet<AP_DETAIL>();
            this.PO_HEADER = new HashSet<PO_HEADER>();
            this.RO_HEADER = new HashSet<RO_HEADER>();
        }
    
        public decimal APA_AUTO_KEY { get; set; }
        public decimal GLA_AUTO_KEY { get; set; }
        public decimal CMP_AUTO_KEY { get; set; }
        public Nullable<decimal> TMC_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSCM_AUTO_KEY { get; set; }
        public string AP_CONTROL_NUMBER { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<decimal> FOREIGN_BALANCE { get; set; }
        public Nullable<System.DateTime> LAST_PAYMENT_DATE { get; set; }
        public Nullable<decimal> LAST_PAYMENT_AMOUNT { get; set; }
        public string OPEN_FLAG { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> PLAN_AMOUNT { get; set; }
        public Nullable<decimal> PLAN_DAYS { get; set; }
        public string HOLD_PAYMENTS { get; set; }
        public Nullable<decimal> CUR_AUTO_KEY { get; set; }
        public string VENDOR_INVOICE { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public Nullable<System.DateTime> VEND_INVC_DATE { get; set; }
        public string IGNORE_TERMS { get; set; }
        public string PAY_OVERRIDE { get; set; }
        public Nullable<decimal> GLP_FOR_CNC { get; set; }
        public string SDF_APA_001 { get; set; }
        public string SDF_APA_002 { get; set; }
        public string SDF_APA_003 { get; set; }
        public string SDF_APA_004 { get; set; }
        public string SDF_APA_005 { get; set; }
        public string SDF_APA_006 { get; set; }
        public string SDF_APA_007 { get; set; }
        public string SDF_APA_008 { get; set; }
        public string SDF_APA_009 { get; set; }
        public string SDF_APA_010 { get; set; }
        public string PREPAY_FLAG { get; set; }
        public Nullable<decimal> VEND_INVC_TOTAL { get; set; }
        public Nullable<decimal> VEND_INVC_FRGN_TOTAL { get; set; }
        public Nullable<decimal> DPT_AUTO_KEY { get; set; }
        public string MANUAL { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string TRACK_CHANGES { get; set; }
    
        public virtual ICollection<AP_DETAIL> AP_DETAIL { get; set; }
        public virtual ICollection<PO_HEADER> PO_HEADER { get; set; }
        public virtual ICollection<RO_HEADER> RO_HEADER { get; set; }
        public virtual COMPANy COMPANy { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
