//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_DETAIL
    {
        public decimal APD_AUTO_KEY { get; set; }
        public decimal APA_AUTO_KEY { get; set; }
        public Nullable<decimal> GLD_AUTO_KEY { get; set; }
        public Nullable<decimal> POH_AUTO_KEY { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<decimal> FOREIGN_AMOUNT { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public System.DateTime TRAN_DATE { get; set; }
        public string PENDING { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public string SYSTEM_CREATED { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> CKD_AUTO_KEY { get; set; }
        public Nullable<decimal> RRH_AUTO_KEY { get; set; }
        public Nullable<decimal> ROH_AUTO_KEY { get; set; }
        public string RECONCILE_ENTRY { get; set; }
        public string GAIN_LOSS { get; set; }
        public Nullable<decimal> GL_TRANS_LINK { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> LTC_AUTO_KEY { get; set; }
        public Nullable<decimal> WCH_AUTO_KEY { get; set; }
        public Nullable<decimal> INH_AUTO_KEY { get; set; }
        public string SDF_APD_001 { get; set; }
        public string SDF_APD_002 { get; set; }
        public string SDF_APD_003 { get; set; }
        public string SDF_APD_004 { get; set; }
        public string SDF_APD_005 { get; set; }
        public string SDF_APD_006 { get; set; }
        public string SDF_APD_007 { get; set; }
        public string SDF_APD_008 { get; set; }
        public string SDF_APD_009 { get; set; }
        public string SDF_APD_010 { get; set; }
        public string CLOSED_UPDATE { get; set; }
        public string OVERRIDE_1099 { get; set; }
        public Nullable<decimal> BOX_1099 { get; set; }
        public Nullable<decimal> WOO_AUTO_KEY { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public Nullable<decimal> WOT_AUTO_KEY { get; set; }
        public Nullable<decimal> PNM_CHARGE { get; set; }
    
        public virtual AP_ACCOUNT AP_ACCOUNT { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER { get; set; }
        public virtual INVC_HEADER INVC_HEADER { get; set; }
        public virtual PO_HEADER PO_HEADER { get; set; }
        public virtual RO_HEADER RO_HEADER { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
