//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION_CODES
    {
        public APPLICATION_CODES()
        {
            this.CQ_DETAIL = new HashSet<CQ_DETAIL>();
            this.PARTS_MASTER = new HashSet<PARTS_MASTER>();
            this.PO_DETAIL = new HashSet<PO_DETAIL>();
            this.RO_DETAIL = new HashSet<RO_DETAIL>();
            this.SO_DETAIL = new HashSet<SO_DETAIL>();
            this.PART_APPLICATION_CODES = new HashSet<PART_APPLICATION_CODES>();
        }
    
        public decimal APC_AUTO_KEY { get; set; }
        public string APPLICATION_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CANNOT_MODIFY { get; set; }
        public decimal SEQUENCE { get; set; }
        public string CONVERTED { get; set; }
        public string SDF_APC_001 { get; set; }
        public string SDF_APC_002 { get; set; }
        public string SDF_APC_003 { get; set; }
        public string SDF_APC_004 { get; set; }
        public string SDF_APC_005 { get; set; }
        public string SDF_APC_006 { get; set; }
        public string SDF_APC_007 { get; set; }
        public string SDF_APC_008 { get; set; }
        public string SDF_APC_009 { get; set; }
        public string SDF_APC_010 { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public string HISTORICAL { get; set; }
        public string APC_UDF_001 { get; set; }
        public string APC_UDF_002 { get; set; }
        public string APC_UDF_003 { get; set; }
        public string APC_UDF_004 { get; set; }
    
        public virtual ICollection<CQ_DETAIL> CQ_DETAIL { get; set; }
        public virtual ICollection<PARTS_MASTER> PARTS_MASTER { get; set; }
        public virtual ICollection<PO_DETAIL> PO_DETAIL { get; set; }
        public virtual ICollection<RO_DETAIL> RO_DETAIL { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL { get; set; }
        public virtual ICollection<PART_APPLICATION_CODES> PART_APPLICATION_CODES { get; set; }
    }
}
