//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AR_ACCOUNT
    {
        public AR_ACCOUNT()
        {
            this.AR_DETAIL = new HashSet<AR_DETAIL>();
        }
    
        public decimal ARA_AUTO_KEY { get; set; }
        public decimal GLA_AUTO_KEY { get; set; }
        public decimal CMP_AUTO_KEY { get; set; }
        public Nullable<decimal> TMC_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSCM_AUTO_KEY { get; set; }
        public string AR_CONTROL_NUMBER { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<decimal> FOREIGN_BALANCE { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public Nullable<System.DateTime> LAST_PAYMENT_DATE { get; set; }
        public Nullable<decimal> LAST_PAYMENT_AMOUNT { get; set; }
        public string OPEN_FLAG { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public string NOTES { get; set; }
        public decimal CUR_AUTO_KEY { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public string COMPANY_PO_NUMBER { get; set; }
        public string WARRANTY_ACCOUNT { get; set; }
        public string SDF_ARA_001 { get; set; }
        public string SDF_ARA_002 { get; set; }
        public string SDF_ARA_003 { get; set; }
        public string SDF_ARA_004 { get; set; }
        public string SDF_ARA_005 { get; set; }
        public string SDF_ARA_006 { get; set; }
        public string SDF_ARA_007 { get; set; }
        public string SDF_ARA_008 { get; set; }
        public string SDF_ARA_009 { get; set; }
        public string SDF_ARA_010 { get; set; }
        public Nullable<decimal> ACT_AUTO_KEY { get; set; }
        public string PREPAY_FLAG { get; set; }
        public string MANUAL { get; set; }
        public string TRACK_CHANGES { get; set; }
    
        public virtual ICollection<AR_DETAIL> AR_DETAIL { get; set; }
        public virtual COMPANy COMPANy { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
