//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AR_DETAIL
    {
        public decimal ARD_AUTO_KEY { get; set; }
        public decimal ARA_AUTO_KEY { get; set; }
        public Nullable<decimal> GLD_AUTO_KEY { get; set; }
        public Nullable<decimal> INH_AUTO_KEY { get; set; }
        public Nullable<decimal> WCH_AUTO_KEY { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<decimal> FOREIGN_AMOUNT { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public System.DateTime TRAN_DATE { get; set; }
        public string PENDING { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public string SYSTEM_CREATED { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> CRD_AUTO_KEY { get; set; }
        public string RECONCILE_ENTRY { get; set; }
        public string GAIN_LOSS { get; set; }
        public Nullable<decimal> GL_TRANS_LINK { get; set; }
        public Nullable<decimal> EXCH_ORIG_STM { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMMISSION_FLAG { get; set; }
        public string SDF_ARD_001 { get; set; }
        public string SDF_ARD_002 { get; set; }
        public string SDF_ARD_003 { get; set; }
        public string SDF_ARD_004 { get; set; }
        public string SDF_ARD_005 { get; set; }
        public string SDF_ARD_006 { get; set; }
        public string SDF_ARD_007 { get; set; }
        public string SDF_ARD_008 { get; set; }
        public string SDF_ARD_009 { get; set; }
        public string SDF_ARD_010 { get; set; }
        public string CLOSED_UPDATE { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
    
        public virtual AR_ACCOUNT AR_ACCOUNT { get; set; }
        public virtual INVC_HEADER INVC_HEADER { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
