//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMISSION_CODES
    {
        public COMMISSION_CODES()
        {
            this.INVC_DETAIL = new HashSet<INVC_DETAIL>();
            this.INVC_DETAIL1 = new HashSet<INVC_DETAIL>();
            this.SO_DETAIL = new HashSet<SO_DETAIL>();
            this.INVC_DETAIL2 = new HashSet<INVC_DETAIL>();
            this.SO_DETAIL1 = new HashSet<SO_DETAIL>();
            this.SO_DETAIL2 = new HashSet<SO_DETAIL>();
            this.INVC_DETAIL3 = new HashSet<INVC_DETAIL>();
            this.SO_DETAIL3 = new HashSet<SO_DETAIL>();
        }
    
        public decimal CMC_AUTO_KEY { get; set; }
        public string COMMISSION_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal COMM_RATE { get; set; }
        public string SDF_CMC_001 { get; set; }
        public string SDF_CMC_002 { get; set; }
        public string SDF_CMC_003 { get; set; }
        public string SDF_CMC_004 { get; set; }
        public string SDF_CMC_005 { get; set; }
        public string SDF_CMC_006 { get; set; }
        public string SDF_CMC_007 { get; set; }
        public string SDF_CMC_008 { get; set; }
        public string SDF_CMC_009 { get; set; }
        public string SDF_CMC_010 { get; set; }
    
        public virtual ICollection<INVC_DETAIL> INVC_DETAIL { get; set; }
        public virtual ICollection<INVC_DETAIL> INVC_DETAIL1 { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL { get; set; }
        public virtual ICollection<INVC_DETAIL> INVC_DETAIL2 { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL1 { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL2 { get; set; }
        public virtual ICollection<INVC_DETAIL> INVC_DETAIL3 { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL3 { get; set; }
    }
}
