//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_LIST
    {
        public decimal CLT_AUTO_KEY { get; set; }
        public decimal LST_AUTO_KEY { get; set; }
        public Nullable<decimal> CMP_AUTO_KEY { get; set; }
        public Nullable<decimal> RDX_AUTO_KEY { get; set; }
        public string DEFERRED { get; set; }
        public string SDF_CLT_001 { get; set; }
        public string SDF_CLT_002 { get; set; }
        public string SDF_CLT_003 { get; set; }
        public string SDF_CLT_004 { get; set; }
        public string SDF_CLT_005 { get; set; }
        public string SDF_CLT_006 { get; set; }
        public string SDF_CLT_007 { get; set; }
        public string SDF_CLT_008 { get; set; }
        public string SDF_CLT_009 { get; set; }
        public string SDF_CLT_010 { get; set; }
    
        public virtual COMPANy COMPANy { get; set; }
    }
}
