//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_AGENTS
    {
        public decimal AGN_AUTO_KEY { get; set; }
        public decimal CMP_AUTO_KEY { get; set; }
        public string CONVERTED { get; set; }
        public string SDF_CMP_001 { get; set; }
        public string SDF_CMP_002 { get; set; }
        public string SDF_CMP_003 { get; set; }
        public string SDF_CMP_004 { get; set; }
        public string SDF_CMP_005 { get; set; }
        public string SDF_CMP_006 { get; set; }
        public string SDF_CMP_007 { get; set; }
        public string SDF_CMP_008 { get; set; }
        public string SDF_CMP_009 { get; set; }
        public string SDF_CMP_010 { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
    
        public virtual AGENT AGENT { get; set; }
        public virtual COMPANy COMPANy { get; set; }
    }
}
