//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANy
    {
        public COMPANy()
        {
            this.AC_CONTROL = new HashSet<AC_CONTROL>();
            this.AP_ACCOUNT = new HashSet<AP_ACCOUNT>();
            this.AR_ACCOUNT = new HashSet<AR_ACCOUNT>();
            this.STOCKs = new HashSet<STOCK>();
            this.CUSTOMER_DISCOUNT_CODES = new HashSet<CUSTOMER_DISCOUNT_CODES>();
            this.COMPANY_LIST = new HashSet<COMPANY_LIST>();
            this.COMPANIES1 = new HashSet<COMPANy>();
            this.COMPANY_AGENTS = new HashSet<COMPANY_AGENTS>();
            this.CQ_HEADER = new HashSet<CQ_HEADER>();
            this.SM_HEADER = new HashSet<SM_HEADER>();
            this.INVC_HEADER = new HashSet<INVC_HEADER>();
            this.PO_HEADER = new HashSet<PO_HEADER>();
            this.RO_HEADER = new HashSet<RO_HEADER>();
            this.SM_HEADER1 = new HashSet<SM_HEADER>();
            this.SO_HEADER = new HashSet<SO_HEADER>();
            this.STOCKs1 = new HashSet<STOCK>();
            this.SYS_USERS = new HashSet<SYS_USERS>();
            this.STOCKs2 = new HashSet<STOCK>();
            this.RC_HEADER = new HashSet<RC_HEADER>();
            this.RC_HEADER1 = new HashSet<RC_HEADER>();
        }
    
        public decimal CMP_AUTO_KEY { get; set; }
        public Nullable<decimal> CUR_AUTO_KEY { get; set; }
        public Nullable<decimal> SVC_AUTO_KEY { get; set; }
        public Nullable<decimal> TMC_AUTO_KEY { get; set; }
        public Nullable<decimal> TXT_AUTO_KEY { get; set; }
        public Nullable<decimal> CLC_AUTO_KEY { get; set; }
        public Nullable<decimal> FPC_AUTO_KEY { get; set; }
        public string COMPANY_CODE { get; set; }
        public string SITE_CODE { get; set; }
        public string ATTENTION { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ALT_PHONE_NUMBER { get; set; }
        public string CITY { get; set; }
        public string COMPANY_ABBREV { get; set; }
        public string COMPANY_NAME { get; set; }
        public string CONTACT_NAME { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<decimal> CURRENT_BALANCE { get; set; }
        public Nullable<System.DateTime> COMPANY_BRIDGE_DATE { get; set; }
        public string CUSTOMER_FLAG { get; set; }
        public string DEPARTMENT { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public string FAX_NUMBER { get; set; }
        public string FAX_BROADCAST_FLAG { get; set; }
        public string INVC_DOC_STYLE { get; set; }
        public Nullable<System.DateTime> LAST_SALE_DATE { get; set; }
        public string MAIL_MERGE_FLAG { get; set; }
        public Nullable<decimal> MAX_CREDIT { get; set; }
        public string MISCELLANEOUS { get; set; }
        public string NOTES { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string PHONE_STRIPPED { get; set; }
        public string PO_DOC_STYLE { get; set; }
        public string RESALE_NUMBER { get; set; }
        public string SHIP_COUNTRY { get; set; }
        public string SHIP_CITY { get; set; }
        public string SHIP_STATE { get; set; }
        public string SHIP_ADDRESS1 { get; set; }
        public string SHIP_ADDRESS2 { get; set; }
        public string SHIP_ADDRESS3 { get; set; }
        public string SHIP_ZIP_CODE { get; set; }
        public string STATE { get; set; }
        public string SUPPLIER_ID { get; set; }
        public string VENDOR_FLAG { get; set; }
        public Nullable<System.DateTime> VENDOR_BRIDGE_DATE { get; set; }
        public Nullable<decimal> YTD_SALES { get; set; }
        public string ZIP_CODE { get; set; }
        public string CV_UDF_001 { get; set; }
        public string CV_UDF_002 { get; set; }
        public string CV_UDF_003 { get; set; }
        public string CV_UDF_004 { get; set; }
        public string CV_UDF_005 { get; set; }
        public string CV_UDF_006 { get; set; }
        public string CV_UDF_007 { get; set; }
        public string CV_UDF_008 { get; set; }
        public string CV_UDF_009 { get; set; }
        public string CV_UDF_010 { get; set; }
        public string CV_UDF_011 { get; set; }
        public string CV_UDF_012 { get; set; }
        public string CV_UDF_013 { get; set; }
        public string CV_UDF_014 { get; set; }
        public string CV_UDF_015 { get; set; }
        public string COMPANY_NAME_UPPER { get; set; }
        public string COMPANY_CODE_UPPER { get; set; }
        public string SITE_CODE_UPPER { get; set; }
        public string TAX_ID { get; set; }
        public string VAT_NUMBER { get; set; }
        public string SEND_1099 { get; set; }
        public Nullable<decimal> GLA_AR { get; set; }
        public Nullable<decimal> GLA_AP { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string IQ_ENABLE_QTY { get; set; }
        public string IQ_ENABLE_PRICE { get; set; }
        public string IQ_ENABLE_CONDITION { get; set; }
        public string IQ_ENABLE_STOCK { get; set; }
        public string IQ_ENABLE_TIMELIFE { get; set; }
        public string IQ_ENABLE_RFQ { get; set; }
        public string IQ_ENABLE_PO { get; set; }
        public Nullable<decimal> SYSUR_IQ_NOTIFY_RFQ { get; set; }
        public Nullable<decimal> SYSUR_IQ_NOTIFY_PO { get; set; }
        public string ALLOW_ANY { get; set; }
        public string ALLOW_CQ { get; set; }
        public string ALLOW_VQ { get; set; }
        public string ALLOW_PO { get; set; }
        public string ALLOW_SO { get; set; }
        public string ALLOW_IN { get; set; }
        public string ALLOW_RO { get; set; }
        public Nullable<decimal> IQ_LOC { get; set; }
        public string IQ_USER { get; set; }
        public string IQ_PASS { get; set; }
        public string IQ_RESPONSE_EMAIL { get; set; }
        public string IQ_HOSTNAME_OVERRIDE { get; set; }
        public Nullable<decimal> IQ_SEQ { get; set; }
        public string IQ_CURRENCY { get; set; }
        public Nullable<decimal> AGN_AUTO_KEY { get; set; }
        public Nullable<decimal> SPN_AUTO_KEY { get; set; }
        public string FAX_STRIPPED { get; set; }
        public string DEFERRED_REC { get; set; }
        public string SPEC_2000 { get; set; }
        public string CAP_RESTRICT_LEVEL { get; set; }
        public Nullable<decimal> AP_TOTAL { get; set; }
        public string IQ_VIEW_RFQ { get; set; }
        public string IQ_VIEW_PO { get; set; }
        public string IQ_QUOTE_TO_PO { get; set; }
        public string CONVERTED { get; set; }
        public string ILS_CODE { get; set; }
        public string CV_UDF_016 { get; set; }
        public string CV_UDF_017 { get; set; }
        public string CV_UDF_018 { get; set; }
        public string CV_UDF_019 { get; set; }
        public string CV_UDF_020 { get; set; }
        public string CV_UDF_021 { get; set; }
        public string CV_UDF_022 { get; set; }
        public string CV_UDF_023 { get; set; }
        public string CV_UDF_024 { get; set; }
        public string CV_UDF_025 { get; set; }
        public string CQ_WARNING { get; set; }
        public string SO_WARNING { get; set; }
        public string IN_WARNING { get; set; }
        public string VQ_WARNING { get; set; }
        public string PO_WARNING { get; set; }
        public string RO_WARNING { get; set; }
        public string WO_WARNING { get; set; }
        public string ALLOW_WO { get; set; }
        public Nullable<decimal> QUANTUM_ID { get; set; }
        public string ALLOW_CM { get; set; }
        public string CM_WARNING { get; set; }
        public Nullable<decimal> TMC_VEND_OVERRIDE { get; set; }
        public string EB_USERID { get; set; }
        public string DBA { get; set; }
        public Nullable<decimal> CMP_PARENT { get; set; }
        public string MKT_COMPANY_CODE { get; set; }
        public Nullable<decimal> MKC_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> CV_UDF_053 { get; set; }
        public string DEFERRED_RO_REC { get; set; }
        public string USE_MKT { get; set; }
        public string RESTRICTED { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string PRIORITY_VENDOR { get; set; }
        public Nullable<decimal> CREDIT_LIMIT { get; set; }
        public string QB_CUST_LISTID { get; set; }
        public string QB_VEND_LISTID { get; set; }
        public string SDF_CMP_001 { get; set; }
        public string SDF_CMP_002 { get; set; }
        public string SDF_CMP_003 { get; set; }
        public string SDF_CMP_004 { get; set; }
        public string SDF_CMP_005 { get; set; }
        public string SDF_CMP_006 { get; set; }
        public string SDF_CMP_007 { get; set; }
        public string SDF_CMP_008 { get; set; }
        public string SDF_CMP_009 { get; set; }
        public string SDF_CMP_010 { get; set; }
        public string ELC_REQUIRED { get; set; }
        public Nullable<decimal> LABOR_DISCOUNT { get; set; }
        public Nullable<System.DateTime> CV_UDF_054 { get; set; }
        public Nullable<decimal> CNC_AUTO_KEY { get; set; }
        public string ALLOW_WC { get; set; }
        public string WC_WARNING { get; set; }
        public string ALLOW_WQ { get; set; }
        public string WQ_WARNING { get; set; }
        public string ALLOW_WQ_BILL { get; set; }
        public string WQ_BILL_WARNING { get; set; }
        public Nullable<decimal> CORE_DUE_DAYS { get; set; }
        public string DEPT_COMPANY { get; set; }
        public string REQ_VERIFICATION { get; set; }
        public string TRACK_CHANGES { get; set; }
        public Nullable<decimal> GLD_AR { get; set; }
        public Nullable<decimal> GLD_AP { get; set; }
        public Nullable<decimal> COC_AUTO_KEY { get; set; }
        public string SHIP_NAME { get; set; }
        public Nullable<decimal> DTC_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED { get; set; }
        public Nullable<decimal> SYSUR_MODIFIED { get; set; }
        public Nullable<decimal> GLD_AP_PREPAY { get; set; }
        public Nullable<decimal> GLD_AR_PREPAY { get; set; }
        public string EDI_NUMBER { get; set; }
        public Nullable<decimal> EDI_SEQUENCE { get; set; }
        public string LANG_CODE { get; set; }
        public string ENQUEUE_MSG { get; set; }
        public string ROUTING_NUMBER { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public string ACH_VENDOR { get; set; }
        public Nullable<decimal> GLD_AP_EXPENSE { get; set; }
        public string WEB_SITE { get; set; }
        public string INVOICE_EMAIL { get; set; }
        public Nullable<decimal> GLD_AP_SUSPENSE { get; set; }
        public string INTERNAL_FLAG { get; set; }
        public Nullable<decimal> COC_OFFICE { get; set; }
        public Nullable<System.DateTime> APPROVAL_EXPIRE { get; set; }
        public Nullable<decimal> APR_AUTO_KEY { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public string DHL_DELIVERY_DUTY_PAYOR { get; set; }
        public string ALLOW_WP { get; set; }
        public string WP_WARNING { get; set; }
        public string VQ_APPROVED { get; set; }
        public Nullable<decimal> CFF_AUTO_KEY { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_ADDRESS1 { get; set; }
        public string BANK_ADDRESS2 { get; set; }
        public string BANK_ADDRESS3 { get; set; }
        public string BANK_COUNTRY_CODE { get; set; }
        public string INTERMEDIATE_BANK_NAME { get; set; }
        public string INTERMEDIATE_BANK_ADDRESS1 { get; set; }
        public string INTERMEDIATE_BANK_ADDRESS2 { get; set; }
        public string INTERMEDIATE_BANK_ADDDRES3 { get; set; }
        public string INTERMEDIATE_BANK_COUNTRY { get; set; }
        public string INTERMEDIATE_BANK_SWIFT { get; set; }
        public string INTERMEDIATE_CLEARING_CODE { get; set; }
        public string INTERMEDIATE_CLEARING_TYPE { get; set; }
        public string SWIFT_CODE { get; set; }
        public string ALLOW_MO { get; set; }
        public string MO_WARNING { get; set; }
        public string ALLOW_PR { get; set; }
        public string PR_WARNING { get; set; }
        public string ALLOW_LC { get; set; }
        public string LC_WARNING { get; set; }
        public string ALLOW_AP { get; set; }
        public string AP_WARNING { get; set; }
        public string ALLOW_CR { get; set; }
        public string CR_WARNING { get; set; }
        public string ALLOW_RR { get; set; }
        public string RR_WARNING { get; set; }
        public string ALLOW_CKM { get; set; }
        public string CKM_WARNING { get; set; }
        public string ALLOW_SMB { get; set; }
        public string SMB_WARNING { get; set; }
        public string ALLOW_SM { get; set; }
        public string SM_WARNING { get; set; }
        public string ALLOW_RI { get; set; }
        public string RI_WARNING { get; set; }
        public string SDF_CMP_011 { get; set; }
        public string SDF_CMP_012 { get; set; }
        public string SDF_CMP_013 { get; set; }
        public string SDF_CMP_014 { get; set; }
        public string SDF_CMP_015 { get; set; }
        public string SDF_CMP_016 { get; set; }
        public string SDF_CMP_017 { get; set; }
        public string SDF_CMP_018 { get; set; }
        public string SDF_CMP_019 { get; set; }
        public string SDF_CMP_020 { get; set; }
        public string RECO { get; set; }
        public string EDD_ID { get; set; }
        public string SMA_WARNING { get; set; }
        public Nullable<decimal> BOX_1099 { get; set; }
        public string REQ_CONTRACT { get; set; }
        public Nullable<decimal> BANK_CHARGES_INDICATOR { get; set; }
        public string PO_COST_METHOD { get; set; }
        public string BUC_CODE { get; set; }
        public string WO_NOTES { get; set; }
        public string MSG_VENDOR { get; set; }
        public string AMAZON_BUCKET { get; set; }
        public string QQM_SENDER_ID { get; set; }
        public Nullable<decimal> MFG_AUTO_KEY { get; set; }
        public string INTEGRATED_MANUALS { get; set; }
        public string SDF_CMP_021 { get; set; }
        public string TRACKER_VISIBLE_PORTAL { get; set; }
        public string BOA_WARNING { get; set; }
        public string PBH_FLAG { get; set; }
        public string ALLOW_SMS { get; set; }
        public string SMS_WARNING { get; set; }
        public string PMA_RESTRICTED { get; set; }
        public string IBAN_ACCOUNT_NUMBER { get; set; }
    
        public virtual ICollection<AC_CONTROL> AC_CONTROL { get; set; }
        public virtual ICollection<AP_ACCOUNT> AP_ACCOUNT { get; set; }
        public virtual ICollection<AR_ACCOUNT> AR_ACCOUNT { get; set; }
        public virtual ICollection<STOCK> STOCKs { get; set; }
        public virtual ICollection<CUSTOMER_DISCOUNT_CODES> CUSTOMER_DISCOUNT_CODES { get; set; }
        public virtual ICollection<COMPANY_LIST> COMPANY_LIST { get; set; }
        public virtual ICollection<COMPANy> COMPANIES1 { get; set; }
        public virtual COMPANy COMPANy1 { get; set; }
        public virtual ICollection<COMPANY_AGENTS> COMPANY_AGENTS { get; set; }
        public virtual ICollection<CQ_HEADER> CQ_HEADER { get; set; }
        public virtual ICollection<SM_HEADER> SM_HEADER { get; set; }
        public virtual ICollection<INVC_HEADER> INVC_HEADER { get; set; }
        public virtual ICollection<PO_HEADER> PO_HEADER { get; set; }
        public virtual ICollection<RO_HEADER> RO_HEADER { get; set; }
        public virtual ICollection<SM_HEADER> SM_HEADER1 { get; set; }
        public virtual ICollection<SO_HEADER> SO_HEADER { get; set; }
        public virtual ICollection<STOCK> STOCKs1 { get; set; }
        public virtual ICollection<SYS_USERS> SYS_USERS { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual ICollection<STOCK> STOCKs2 { get; set; }
        public virtual ICollection<RC_HEADER> RC_HEADER { get; set; }
        public virtual ICollection<RC_HEADER> RC_HEADER1 { get; set; }
        public virtual SYS_USERS SYS_USERS1 { get; set; }
        public virtual SYS_USERS SYS_USERS2 { get; set; }
        public virtual SYS_USERS SYS_USERS3 { get; set; }
    }
}
