//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQ_DETAIL
    {
        public CQ_DETAIL()
        {
            this.SO_DETAIL = new HashSet<SO_DETAIL>();
        }
    
        public decimal CQD_AUTO_KEY { get; set; }
        public Nullable<decimal> STM_AUTO_KEY { get; set; }
        public Nullable<decimal> PRI_AUTO_KEY { get; set; }
        public decimal PNM_AUTO_KEY { get; set; }
        public Nullable<decimal> PCC_AUTO_KEY { get; set; }
        public Nullable<decimal> UOM_AUTO_KEY { get; set; }
        public Nullable<decimal> DVC_AUTO_KEY { get; set; }
        public decimal CQH_AUTO_KEY { get; set; }
        public Nullable<decimal> QCC_AUTO_KEY { get; set; }
        public Nullable<decimal> ALT_PNM_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public string ANSWER_FLAG { get; set; }
        public Nullable<decimal> CORE_CHARGE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public string EXCHANGE_TYPE { get; set; }
        public string ITEM_NOTES { get; set; }
        public decimal ITEM_NUMBER { get; set; }
        public Nullable<decimal> LIST_PRICE { get; set; }
        public string NO_QUOTE_FLAG { get; set; }
        public Nullable<System.DateTime> QUOTE_DATE { get; set; }
        public Nullable<decimal> QTY_QUOTED { get; set; }
        public Nullable<decimal> QTY_REQ { get; set; }
        public string QUOTE_AS_TYPE { get; set; }
        public string TAG_FLAG { get; set; }
        public string TOTALS_FLAG { get; set; }
        public Nullable<decimal> UNIT_COST { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string ILS_QUERY_CODE { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public string CALC_TAX { get; set; }
        public Nullable<decimal> PERIOD_PRICE { get; set; }
        public string BILLING_PERIOD { get; set; }
        public Nullable<decimal> PERIODS_PER_CONTRACT { get; set; }
        public Nullable<decimal> PBH_RATE { get; set; }
        public Nullable<decimal> WOB_AUTO_KEY { get; set; }
        public string LETTER_FLAG { get; set; }
        public Nullable<decimal> SPN_AUTO_KEY { get; set; }
        public Nullable<decimal> AGN_AUTO_KEY { get; set; }
        public string CUST_REF { get; set; }
        public string SOD_LINK { get; set; }
        public Nullable<decimal> CUSTOMER_PRICE { get; set; }
        public Nullable<decimal> FOREIGN_LIST_PRICE { get; set; }
        public Nullable<decimal> ROD_AUTO_KEY { get; set; }
        public Nullable<decimal> CTS_AUTO_KEY { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string TAGGED_BY { get; set; }
        public Nullable<System.DateTime> TAG_DATE { get; set; }
        public string CONVERTED { get; set; }
        public Nullable<decimal> SCC_AUTO_KEY { get; set; }
        public string DELIVERY_DESC { get; set; }
        public string EXCH_COST_METHOD { get; set; }
        public Nullable<decimal> SYSUR_AUTH { get; set; }
        public Nullable<System.DateTime> CORE_DUE_DATE { get; set; }
        public string BILL_CORE_CHARGE { get; set; }
        public string LOAN { get; set; }
        public Nullable<decimal> DSC_AUTO_KEY { get; set; }
        public string SO_FLAG { get; set; }
        public string ROUTE_CODE { get; set; }
        public string ROUTE_DESC { get; set; }
        public Nullable<decimal> PDL_AUTO_KEY { get; set; }
        public Nullable<decimal> MKT_CQD { get; set; }
        public string SOURCE_PN { get; set; }
        public string MKT_NOTES { get; set; }
        public Nullable<decimal> ELC_AUTO_KEY { get; set; }
        public string SDF_CQD_001 { get; set; }
        public string SDF_CQD_002 { get; set; }
        public string SDF_CQD_003 { get; set; }
        public string SDF_CQD_004 { get; set; }
        public string SDF_CQD_005 { get; set; }
        public string SDF_CQD_006 { get; set; }
        public string SDF_CQD_007 { get; set; }
        public string SDF_CQD_008 { get; set; }
        public string SDF_CQD_009 { get; set; }
        public string SDF_CQD_010 { get; set; }
        public string CQ_UDF_001 { get; set; }
        public string CQ_UDF_002 { get; set; }
        public string CQ_UDF_003 { get; set; }
        public string CQ_UDF_004 { get; set; }
        public string CQ_UDF_005 { get; set; }
        public Nullable<decimal> FOREIGN_CORE_CHARGE { get; set; }
        public string MERGE_FLAG { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public string IMPORT_REMARKS { get; set; }
        public Nullable<decimal> OPM_AUTO_KEY { get; set; }
        public Nullable<decimal> COC_AUTO_KEY { get; set; }
        public Nullable<decimal> APC_AUTO_KEY { get; set; }
        public Nullable<decimal> RPP_AUTO_KEY { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public Nullable<decimal> PRI_VENDOR { get; set; }
        public string CREATE_CORE_CHARGE_ITEM { get; set; }
        public Nullable<decimal> MSG_AK { get; set; }
        public string AUTO_PRICE { get; set; }
        public Nullable<System.DateTime> AUTO_PRICE_DATE { get; set; }
        public string EXCLUDE_AUTO { get; set; }
        public Nullable<decimal> SYSUR_MODIFIED_PRICE { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<decimal> QTY_ON_ADD { get; set; }
        public string QQM_MSG_GUID { get; set; }
        public string QQM_ITEM_GUID { get; set; }
    
        public virtual APPLICATION_CODES APPLICATION_CODES { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER { get; set; }
        public virtual SO_CATEGORY_CODES SO_CATEGORY_CODES { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL { get; set; }
        public virtual CQ_HEADER CQ_HEADER { get; set; }
        public virtual PART_CONDITION_CODES PART_CONDITION_CODES { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER1 { get; set; }
        public virtual RO_PIECE_PARTS RO_PIECE_PARTS { get; set; }
        public virtual STOCK STOCK { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
