//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQ_HEADER
    {
        public CQ_HEADER()
        {
            this.CQ_DETAIL = new HashSet<CQ_DETAIL>();
        }
    
        public decimal CQH_AUTO_KEY { get; set; }
        public string CQ_NUMBER { get; set; }
        public Nullable<decimal> CMP_AUTO_KEY { get; set; }
        public Nullable<decimal> AGN_AUTO_KEY { get; set; }
        public Nullable<decimal> CUR_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public Nullable<decimal> AGENT_COMM { get; set; }
        public string ATTENTION { get; set; }
        public string COMPANY_REF_NUMBER { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public string FAX_NUMBER { get; set; }
        public string HISTORICAL_FLAG { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> NUMBER_OF_ITEMS { get; set; }
        public Nullable<decimal> TOTAL_COST { get; set; }
        public Nullable<decimal> TOTAL_PRICE { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string PRINTED { get; set; }
        public Nullable<decimal> SYSCM_AUTO_KEY { get; set; }
        public Nullable<decimal> DPT_AUTO_KEY { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public Nullable<decimal> TXT_AUTO_KEY { get; set; }
        public string TAX_METHOD { get; set; }
        public Nullable<decimal> SPN_AUTO_KEY { get; set; }
        public Nullable<decimal> TMC_AUTO_KEY { get; set; }
        public string BILL_ADDRESS1 { get; set; }
        public string BILL_ADDRESS2 { get; set; }
        public string BILL_ADDRESS3 { get; set; }
        public string BILL_ADDRESS4 { get; set; }
        public string BILL_ADDRESS5 { get; set; }
        public string SHIP_ADDRESS1 { get; set; }
        public string SHIP_ADDRESS2 { get; set; }
        public string SHIP_ADDRESS3 { get; set; }
        public string SHIP_ADDRESS4 { get; set; }
        public string SHIP_ADDRESS5 { get; set; }
        public Nullable<decimal> CST_AUTO_KEY { get; set; }
        public string BILL_NAME { get; set; }
        public string SHIP_NAME { get; set; }
        public string CONVERTED { get; set; }
        public Nullable<decimal> ACT_AUTO_KEY { get; set; }
        public Nullable<decimal> CQS_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public Nullable<decimal> LAST_VQH { get; set; }
        public string FOB { get; set; }
        public Nullable<decimal> MKT_CQH { get; set; }
        public Nullable<System.DateTime> MKT_SENT { get; set; }
        public string MKT_NOTES { get; set; }
        public Nullable<decimal> USR_AUTO_KEY { get; set; }
        public string SDF_CQH_001 { get; set; }
        public string SDF_CQH_002 { get; set; }
        public string SDF_CQH_003 { get; set; }
        public string SDF_CQH_004 { get; set; }
        public string SDF_CQH_005 { get; set; }
        public string SDF_CQH_006 { get; set; }
        public string SDF_CQH_007 { get; set; }
        public string SDF_CQH_008 { get; set; }
        public string SDF_CQH_009 { get; set; }
        public string SDF_CQH_010 { get; set; }
        public Nullable<decimal> ELC_AUTO_KEY { get; set; }
        public string TRACK_CHANGES { get; set; }
        public Nullable<decimal> COC_AUTO_KEY { get; set; }
        public string UDF_CQH_001 { get; set; }
        public string UDF_CQH_002 { get; set; }
        public string UDF_CQH_003 { get; set; }
        public string UDF_CQH_004 { get; set; }
        public string UDF_CQH_005 { get; set; }
        public Nullable<decimal> MSG_AK_QUOTE { get; set; }
        public Nullable<System.DateTime> EDI_QUOTE_SENT { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<System.DateTime> SENT_DATE { get; set; }
        public string CUST_EDI_CODE { get; set; }
        public string INTERNAL_FLAG { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public Nullable<decimal> CQR_AUTO_KEY { get; set; }
        public Nullable<decimal> DTC_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> UDD_CQH_001 { get; set; }
        public string QQM_MSG_GUID { get; set; }
        public Nullable<decimal> CST_SOLD_TO { get; set; }
    
        public virtual AGENT AGENT { get; set; }
        public virtual COMPANy COMPANy { get; set; }
        public virtual ICollection<CQ_DETAIL> CQ_DETAIL { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual CQ_STATUS CQ_STATUS { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
        public virtual SYS_USERS SYS_USERS1 { get; set; }
    }
}
