//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQ_STATUS
    {
        public CQ_STATUS()
        {
            this.CQ_HEADER = new HashSet<CQ_HEADER>();
        }
    
        public decimal CQS_AUTO_KEY { get; set; }
        public string STATUS_CODE { get; set; }
        public string STATUS_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string IS_DEFAULT { get; set; }
        public string SDF_CQS_001 { get; set; }
        public string SDF_CQS_002 { get; set; }
        public string SDF_CQS_003 { get; set; }
        public string SDF_CQS_004 { get; set; }
        public string SDF_CQS_005 { get; set; }
        public string SDF_CQS_006 { get; set; }
        public string SDF_CQS_007 { get; set; }
        public string SDF_CQS_008 { get; set; }
        public string SDF_CQS_009 { get; set; }
        public string SDF_CQS_010 { get; set; }
    
        public virtual ICollection<CQ_HEADER> CQ_HEADER { get; set; }
    }
}
