//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENCY
    {
        public CURRENCY()
        {
            this.AP_ACCOUNT = new HashSet<AP_ACCOUNT>();
            this.COMPANIES = new HashSet<COMPANy>();
            this.CQ_HEADER = new HashSet<CQ_HEADER>();
            this.INVC_HEADER = new HashSet<INVC_HEADER>();
            this.PARTS_CATALOG = new HashSet<PARTS_CATALOG>();
            this.PARTS_MASTER = new HashSet<PARTS_MASTER>();
            this.PO_HEADER = new HashSet<PO_HEADER>();
            this.RO_HEADER = new HashSet<RO_HEADER>();
            this.RO_PRE_COSTING_CHARGES = new HashSet<RO_PRE_COSTING_CHARGES>();
            this.SM_HEADER = new HashSet<SM_HEADER>();
            this.SO_HEADER = new HashSet<SO_HEADER>();
        }
    
        public decimal CUR_AUTO_KEY { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string CANNOT_MODIFY { get; set; }
        public string COUNTRY { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> EFF_DATE { get; set; }
        public decimal EXCHANGE_RATE { get; set; }
        public string PRINT_STATEMENT { get; set; }
        public Nullable<decimal> GLS_AUTO_KEY { get; set; }
        public string DISPLAY_FORMAT { get; set; }
        public Nullable<decimal> GLA_AUTO_KEY { get; set; }
        public string CONVERTED { get; set; }
        public string SDF_CUR_001 { get; set; }
        public string SDF_CUR_002 { get; set; }
        public string SDF_CUR_003 { get; set; }
        public string SDF_CUR_004 { get; set; }
        public string SDF_CUR_005 { get; set; }
        public string SDF_CUR_006 { get; set; }
        public string SDF_CUR_007 { get; set; }
        public string SDF_CUR_008 { get; set; }
        public string SDF_CUR_009 { get; set; }
        public string SDF_CUR_010 { get; set; }
        public string QB_LIST_ID { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public string HISTORICAL { get; set; }
        public string OVERWRITE_CURRENCY_FORMAT { get; set; }
    
        public virtual ICollection<AP_ACCOUNT> AP_ACCOUNT { get; set; }
        public virtual ICollection<COMPANy> COMPANIES { get; set; }
        public virtual ICollection<CQ_HEADER> CQ_HEADER { get; set; }
        public virtual ICollection<INVC_HEADER> INVC_HEADER { get; set; }
        public virtual ICollection<PARTS_CATALOG> PARTS_CATALOG { get; set; }
        public virtual ICollection<PARTS_MASTER> PARTS_MASTER { get; set; }
        public virtual ICollection<PO_HEADER> PO_HEADER { get; set; }
        public virtual ICollection<RO_HEADER> RO_HEADER { get; set; }
        public virtual ICollection<RO_PRE_COSTING_CHARGES> RO_PRE_COSTING_CHARGES { get; set; }
        public virtual ICollection<SM_HEADER> SM_HEADER { get; set; }
        public virtual ICollection<SO_HEADER> SO_HEADER { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
