//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_DISCOUNT_CODES
    {
        public decimal CDC_AUTO_KEY { get; set; }
        public decimal CMP_AUTO_KEY { get; set; }
        public decimal DSM_AUTO_KEY { get; set; }
        public string SDF_CDC_001 { get; set; }
        public string SDF_CDC_002 { get; set; }
        public string SDF_CDC_003 { get; set; }
        public string SDF_CDC_004 { get; set; }
        public string SDF_CDC_005 { get; set; }
        public string SDF_CDC_006 { get; set; }
        public string SDF_CDC_007 { get; set; }
        public string SDF_CDC_008 { get; set; }
        public string SDF_CDC_009 { get; set; }
        public string SDF_CDC_010 { get; set; }
    
        public virtual COMPANy COMPANy { get; set; }
    }
}
