//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.AP_ACCOUNT = new HashSet<AP_ACCOUNT>();
            this.CQ_HEADER = new HashSet<CQ_HEADER>();
            this.STOCKs = new HashSet<STOCK>();
            this.SYS_USERS = new HashSet<SYS_USERS>();
            this.INVC_HEADER = new HashSet<INVC_HEADER>();
            this.PARTS_MASTER = new HashSet<PARTS_MASTER>();
            this.PO_HEADER = new HashSet<PO_HEADER>();
            this.RO_HEADER = new HashSet<RO_HEADER>();
            this.SO_HEADER = new HashSet<SO_HEADER>();
        }
    
        public decimal DPT_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSCM_AUTO_KEY { get; set; }
        public Nullable<decimal> GLS_AUTO_KEY { get; set; }
        public string DEPT_NAME { get; set; }
        public Nullable<decimal> DIV_AUTO_KEY { get; set; }
        public string CONVERTED { get; set; }
        public string SDF_DPT_001 { get; set; }
        public string SDF_DPT_002 { get; set; }
        public string SDF_DPT_003 { get; set; }
        public string SDF_DPT_004 { get; set; }
        public string SDF_DPT_005 { get; set; }
        public string SDF_DPT_006 { get; set; }
        public string SDF_DPT_007 { get; set; }
        public string SDF_DPT_008 { get; set; }
        public string SDF_DPT_009 { get; set; }
        public string SDF_DPT_010 { get; set; }
        public string RESTRICT_STOCK { get; set; }
        public string OVERRIDE_ADDRESS { get; set; }
        public string ADDRESS_LINE1 { get; set; }
        public string ADDRESS_LINE2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public Nullable<decimal> COC_AUTO_KEY { get; set; }
        public Nullable<decimal> GEO_AUTO_KEY { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public string PM_FLAG { get; set; }
        public Nullable<decimal> NON_ACC_WOT { get; set; }
        public Nullable<decimal> NON_ACC_WOK { get; set; }
        public Nullable<decimal> NON_ACC_PNM { get; set; }
    
        public virtual ICollection<AP_ACCOUNT> AP_ACCOUNT { get; set; }
        public virtual ICollection<CQ_HEADER> CQ_HEADER { get; set; }
        public virtual ICollection<STOCK> STOCKs { get; set; }
        public virtual ICollection<SYS_USERS> SYS_USERS { get; set; }
        public virtual ICollection<INVC_HEADER> INVC_HEADER { get; set; }
        public virtual ICollection<PARTS_MASTER> PARTS_MASTER { get; set; }
        public virtual ICollection<PO_HEADER> PO_HEADER { get; set; }
        public virtual ICollection<RO_HEADER> RO_HEADER { get; set; }
        public virtual ICollection<SO_HEADER> SO_HEADER { get; set; }
    }
}
