//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVC_HEADER
    {
        public INVC_HEADER()
        {
            this.AP_DETAIL = new HashSet<AP_DETAIL>();
            this.AR_DETAIL = new HashSet<AR_DETAIL>();
            this.INVC_DETAIL = new HashSet<INVC_DETAIL>();
        }
    
        public decimal INH_AUTO_KEY { get; set; }
        public string INVC_NUMBER { get; set; }
        public Nullable<decimal> TXT_AUTO_KEY { get; set; }
        public decimal CMP_AUTO_KEY { get; set; }
        public Nullable<decimal> CUR_AUTO_KEY { get; set; }
        public Nullable<decimal> SVC_AUTO_KEY { get; set; }
        public Nullable<decimal> TMC_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public Nullable<decimal> NUMBER_OF_ITEMS { get; set; }
        public Nullable<decimal> TOTAL_COST { get; set; }
        public Nullable<decimal> TOTAL_PRICE { get; set; }
        public string ATTENTION { get; set; }
        public string AIRWAY_BILL { get; set; }
        public string BILL_ADDRESS1 { get; set; }
        public string BILL_ADDRESS2 { get; set; }
        public string BILL_ADDRESS3 { get; set; }
        public string BILL_ADDRESS4 { get; set; }
        public string BILL_ADDRESS5 { get; set; }
        public string BILL_NAME { get; set; }
        public string CLAUSE_LIST { get; set; }
        public string COMPANY_PO_NUMBER { get; set; }
        public string COMPANY_DEPT { get; set; }
        public string INSTRUCTIONS { get; set; }
        public System.DateTime INVOICE_DATE { get; set; }
        public string NOTES { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public string PICKLIST_NOTES { get; set; }
        public Nullable<System.DateTime> PRINT_DATE { get; set; }
        public string QTY_CARTONS { get; set; }
        public string SHIP_ADDRESS1 { get; set; }
        public string SHIP_ADDRESS2 { get; set; }
        public string SHIP_ADDRESS3 { get; set; }
        public string SHIP_ADDRESS4 { get; set; }
        public string SHIP_ADDRESS5 { get; set; }
        public Nullable<int> SHIP_NUMBER { get; set; }
        public string SHIP_NAME { get; set; }
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public string SOLD_BY { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public string WEIGHT { get; set; }
        public string FOB { get; set; }
        public Nullable<int> POST_STATUS { get; set; }
        public string POST_DESC { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string CLOSED_UPDATE { get; set; }
        public Nullable<decimal> DPT_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSCM_AUTO_KEY { get; set; }
        public string FAX_NUMBER { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string TAX_METHOD { get; set; }
        public Nullable<decimal> FOREIGN_AMOUNT { get; set; }
        public Nullable<decimal> SPN_AUTO_KEY { get; set; }
        public Nullable<decimal> AGN_AUTO_KEY { get; set; }
        public Nullable<decimal> CST_AUTO_KEY { get; set; }
        public string TRACKING_NUMBER { get; set; }
        public string TO_PRINT { get; set; }
        public string EXPORTED_FLAG { get; set; }
        public string EXTERNAL_BATCH { get; set; }
        public string CONVERTED { get; set; }
        public Nullable<decimal> ACT_AUTO_KEY { get; set; }
        public Nullable<decimal> SVA_AUTO_KEY { get; set; }
        public Nullable<decimal> PAYMENT_AMT { get; set; }
        public Nullable<decimal> FOREIGN_PMT_AMT { get; set; }
        public Nullable<decimal> EXCH_RATE { get; set; }
        public Nullable<decimal> PMT_AUTO_KEY { get; set; }
        public Nullable<decimal> BNK_AUTO_KEY { get; set; }
        public string CHECK_NUMBER { get; set; }
        public Nullable<decimal> CCR_AUTO_KEY { get; set; }
        public Nullable<decimal> PRH_AUTO_KEY { get; set; }
        public string HAZMAT_NOTES { get; set; }
        public string INVC_TYPE { get; set; }
        public Nullable<System.DateTime> POST_DATE { get; set; }
        public Nullable<decimal> WQH_AUTO_KEY { get; set; }
        public Nullable<decimal> USR_AUTO_KEY { get; set; }
        public Nullable<decimal> MKT_INH { get; set; }
        public string QB_TXNID { get; set; }
        public string QB_TRAN { get; set; }
        public string SDF_INH_001 { get; set; }
        public string SDF_INH_002 { get; set; }
        public string SDF_INH_003 { get; set; }
        public string SDF_INH_004 { get; set; }
        public string SDF_INH_005 { get; set; }
        public string SDF_INH_006 { get; set; }
        public string SDF_INH_007 { get; set; }
        public string SDF_INH_008 { get; set; }
        public string SDF_INH_009 { get; set; }
        public string SDF_INH_010 { get; set; }
        public Nullable<decimal> ELC_AUTO_KEY { get; set; }
        public string PROFORMA_NUMBER { get; set; }
        public Nullable<decimal> SCC_AUTO_KEY { get; set; }
        public Nullable<decimal> COC_AUTO_KEY { get; set; }
        public Nullable<decimal> DTC_AUTO_KEY { get; set; }
        public string IN_UDF_001 { get; set; }
        public Nullable<decimal> SYSUR_POSTED { get; set; }
        public string BATCH_NUMBER { get; set; }
        public Nullable<decimal> MSG_AK_INVC { get; set; }
        public Nullable<System.DateTime> EDI_INVC_SENT { get; set; }
        public Nullable<decimal> WOO_PROGRESS { get; set; }
        public string SKIP_SYNC { get; set; }
        public string TRACK_CHANGES { get; set; }
        public string INTERNAL_FLAG { get; set; }
        public Nullable<decimal> WOO_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<System.DateTime> POST_TIME_STAMP { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public Nullable<decimal> MSG_AK_ASN { get; set; }
        public Nullable<System.DateTime> EDI_ASN_SENT { get; set; }
        public Nullable<decimal> WOO_DEPOSIT { get; set; }
        public string PAYMENT_RECEIVED { get; set; }
        public Nullable<decimal> AMT_RECEIVED { get; set; }
        public string CC_CUSTOMER_NAME { get; set; }
        public string CC_STREET_ADDRESS { get; set; }
        public string CC_CITY_STATE_ZIP { get; set; }
        public Nullable<System.DateTime> EXP_DATE { get; set; }
        public string VISIBLE_PORTAL { get; set; }
    
        public virtual ICollection<AP_DETAIL> AP_DETAIL { get; set; }
        public virtual ICollection<AR_DETAIL> AR_DETAIL { get; set; }
        public virtual COMPANy COMPANy { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<INVC_DETAIL> INVC_DETAIL { get; set; }
        public virtual SO_CATEGORY_CODES SO_CATEGORY_CODES { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
        public virtual SYS_USERS SYS_USERS1 { get; set; }
    }
}
