//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_CONDITION_CODES
    {
        public PART_CONDITION_CODES()
        {
            this.CQ_DETAIL = new HashSet<CQ_DETAIL>();
            this.PO_DETAIL = new HashSet<PO_DETAIL>();
            this.RO_DETAIL = new HashSet<RO_DETAIL>();
            this.SO_DETAIL = new HashSet<SO_DETAIL>();
            this.STOCKs = new HashSet<STOCK>();
            this.RC_DETAIL = new HashSet<RC_DETAIL>();
        }
    
        public decimal PCC_AUTO_KEY { get; set; }
        public string CONDITION_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CANNOT_MODIFY { get; set; }
        public decimal SEQUENCE { get; set; }
        public Nullable<decimal> COND_LEVEL { get; set; }
        public string CONVERTED { get; set; }
        public string ILS_COND { get; set; }
        public string SDF_PCC_001 { get; set; }
        public string SDF_PCC_002 { get; set; }
        public string SDF_PCC_003 { get; set; }
        public string SDF_PCC_004 { get; set; }
        public string SDF_PCC_005 { get; set; }
        public string SDF_PCC_006 { get; set; }
        public string SDF_PCC_007 { get; set; }
        public string SDF_PCC_008 { get; set; }
        public string SDF_PCC_009 { get; set; }
        public string SDF_PCC_010 { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public string VISIBLE_PORTAL { get; set; }
        public string HISTORICAL { get; set; }
    
        public virtual ICollection<CQ_DETAIL> CQ_DETAIL { get; set; }
        public virtual ICollection<PO_DETAIL> PO_DETAIL { get; set; }
        public virtual ICollection<RO_DETAIL> RO_DETAIL { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL { get; set; }
        public virtual ICollection<STOCK> STOCKs { get; set; }
        public virtual ICollection<RC_DETAIL> RC_DETAIL { get; set; }
    }
}
