//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_SPECS
    {
        public decimal PSS_AUTO_KEY { get; set; }
        public decimal SCD_AUTO_KEY { get; set; }
        public decimal PNM_AUTO_KEY { get; set; }
        public string REVISION { get; set; }
        public Nullable<decimal> SHELF_LIFE { get; set; }
        public string SHELF_LIFE_PERIOD { get; set; }
        public string SHELF_LIFE_TYPE { get; set; }
        public string SHELF_LIFE_DESCR { get; set; }
        public string SO_NOTES { get; set; }
        public string PO_NOTES { get; set; }
        public string SHELF_LIFE_NOTES { get; set; }
        public string SDF_PSS_001 { get; set; }
        public string SDF_PSS_002 { get; set; }
        public string SDF_PSS_003 { get; set; }
        public string SDF_PSS_004 { get; set; }
        public string SDF_PSS_005 { get; set; }
    
        public virtual PARTS_MASTER PARTS_MASTER { get; set; }
    }
}
