//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTS_WHS_LOC
    {
        public decimal PWL_AUTO_KEY { get; set; }
        public decimal PNM_AUTO_KEY { get; set; }
        public decimal WHS_AUTO_KEY { get; set; }
        public decimal LOC_AUTO_KEY { get; set; }
    
        public virtual PARTS_MASTER PARTS_MASTER { get; set; }
    }
}
