//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTS_MASTER
    {
        public PARTS_MASTER()
        {
            this.ALTERNATES_PARTS_MASTER = new HashSet<ALTERNATES_PARTS_MASTER>();
            this.ALTERNATES_PARTS_MASTER1 = new HashSet<ALTERNATES_PARTS_MASTER>();
            this.AP_DETAIL = new HashSet<AP_DETAIL>();
            this.CQ_DETAIL = new HashSet<CQ_DETAIL>();
            this.CQ_DETAIL1 = new HashSet<CQ_DETAIL>();
            this.INVC_DETAIL = new HashSet<INVC_DETAIL>();
            this.PART_APPLICATION_CODES = new HashSet<PART_APPLICATION_CODES>();
            this.PART_SPECS = new HashSet<PART_SPECS>();
            this.PARTS_CATALOG = new HashSet<PARTS_CATALOG>();
            this.PO_DETAIL = new HashSet<PO_DETAIL>();
            this.SO_DETAIL = new HashSet<SO_DETAIL>();
            this.PI_DETAIL = new HashSet<PI_DETAIL>();
            this.PO_DETAIL1 = new HashSet<PO_DETAIL>();
            this.PARTS_WHS_LOC = new HashSet<PARTS_WHS_LOC>();
            this.RO_DETAIL = new HashSet<RO_DETAIL>();
            this.RO_PRE_COSTING_CHARGES = new HashSet<RO_PRE_COSTING_CHARGES>();
            this.RO_PIECE_PARTS = new HashSet<RO_PIECE_PARTS>();
            this.SM_DETAIL = new HashSet<SM_DETAIL>();
            this.SM_HISTORY = new HashSet<SM_HISTORY>();
            this.SO_DETAIL1 = new HashSet<SO_DETAIL>();
            this.STOCKs = new HashSet<STOCK>();
            this.RC_DETAIL = new HashSet<RC_DETAIL>();
            this.RC_DETAIL1 = new HashSet<RC_DETAIL>();
            this.RO_DETAIL1 = new HashSet<RO_DETAIL>();
        }
    
        public decimal PNM_AUTO_KEY { get; set; }
        public Nullable<decimal> CUR_AUTO_KEY { get; set; }
        public Nullable<decimal> PNG_AUTO_KEY { get; set; }
        public Nullable<decimal> PTC_AUTO_KEY { get; set; }
        public Nullable<decimal> UOM_AUTO_KEY { get; set; }
        public Nullable<decimal> IFC_AUTO_KEY { get; set; }
        public decimal MFG_AUTO_KEY { get; set; }
        public string MASTER_FLAG { get; set; }
        public Nullable<decimal> APC_AUTO_KEY { get; set; }
        public string PN { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> LIST_PRICE { get; set; }
        public Nullable<System.DateTime> LIST_PRICE_DATE { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> QTY_MIN_SELL { get; set; }
        public string REMARKS { get; set; }
        public string SERIALIZED { get; set; }
        public string IC_UDF_001 { get; set; }
        public string IC_UDF_002 { get; set; }
        public string IC_UDF_003 { get; set; }
        public string IC_UDF_004 { get; set; }
        public string PN_STRIPPED { get; set; }
        public Nullable<decimal> QTY_MIN_NEW { get; set; }
        public Nullable<decimal> QTY_MIN_OH { get; set; }
        public Nullable<decimal> QTY_MIN_OTHER { get; set; }
        public Nullable<decimal> QTY_OH { get; set; }
        public Nullable<decimal> QTY_RESERVED { get; set; }
        public Nullable<decimal> QTY_AVAILABLE { get; set; }
        public string CHARGE { get; set; }
        public Nullable<decimal> CHARGE_COST { get; set; }
        public string PN_UPPER { get; set; }
        public string DESCRIPTION_UPPER { get; set; }
        public string IC_UDF_004_UPPER { get; set; }
        public Nullable<System.DateTime> QTY_CHANGE_DATE { get; set; }
        public Nullable<decimal> GLD_SALE { get; set; }
        public Nullable<decimal> GLD_COG { get; set; }
        public Nullable<decimal> GLD_INV { get; set; }
        public Nullable<decimal> GLD_ADJ { get; set; }
        public string IQ_ENABLE { get; set; }
        public string ACTIVE_PART { get; set; }
        public Nullable<decimal> PXC_AUTO_KEY { get; set; }
        public string EXPENDABLE { get; set; }
        public Nullable<decimal> FOREIGN_LIST_PRICE { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public string CLSD_UPDATE { get; set; }
        public string CONVERTED { get; set; }
        public string HAZARD_MATERIAL { get; set; }
        public Nullable<decimal> DEF_OVHL_COST { get; set; }
        public string PN_UPDATED { get; set; }
        public string WARNING_MESSAGE { get; set; }
        public Nullable<decimal> DSC_AUTO_KEY { get; set; }
        public Nullable<decimal> EXCH_LIST_PRICE { get; set; }
        public Nullable<decimal> FOREIGN_EXCH_LIST_PRICE { get; set; }
        public Nullable<decimal> EXCH_CORE_CHARGE { get; set; }
        public Nullable<decimal> LOC_AUTO_KEY { get; set; }
        public Nullable<decimal> WHS_AUTO_KEY { get; set; }
        public Nullable<decimal> MDL_AUTO_KEY { get; set; }
        public Nullable<decimal> GLD_FIXED_OVERHEAD { get; set; }
        public Nullable<decimal> GLD_VAR_OVERHEAD { get; set; }
        public Nullable<decimal> DEF_CORE_VALUE { get; set; }
        public string SO_TYPE { get; set; }
        public Nullable<decimal> SCC_AUTO_KEY { get; set; }
        public string AC_CHARGE { get; set; }
        public string PN_ORIGINAL { get; set; }
        public Nullable<decimal> QTY_MIN { get; set; }
        public Nullable<decimal> QTY_MAX { get; set; }
        public Nullable<decimal> LEAD_DAYS { get; set; }
        public Nullable<System.DateTime> MIN_MAX_DATE { get; set; }
        public string CLASS_FLAG { get; set; }
        public string TRACK_CHANGES { get; set; }
        public Nullable<decimal> CFL_AUTO_KEY { get; set; }
        public Nullable<decimal> STC_AUTO_KEY { get; set; }
        public string SHELF_LIFE { get; set; }
        public string TRACK_RELIABILITY { get; set; }
        public Nullable<decimal> ILS_NE { get; set; }
        public Nullable<decimal> ILS_NS { get; set; }
        public Nullable<decimal> ILS_OH { get; set; }
        public Nullable<decimal> ILS_AR { get; set; }
        public Nullable<decimal> ILS_SV { get; set; }
        public Nullable<decimal> ILS_NA { get; set; }
        public Nullable<decimal> WC_DEF_HOURS { get; set; }
        public Nullable<decimal> EXPORT_ID { get; set; }
        public string PROPER_SHIP_NAME { get; set; }
        public string PACKING_INSTR { get; set; }
        public string PACKING_TYPE { get; set; }
        public string HAZMAT_AUTHORIZATION { get; set; }
        public string IC_UDF_011 { get; set; }
        public string IC_UDF_012 { get; set; }
        public string IC_UDF_013 { get; set; }
        public string IC_UDF_014 { get; set; }
        public string TECHNICAL_NAME { get; set; }
        public string AVREF_COMMENTS { get; set; }
        public string AVREF_FLAG { get; set; }
        public string HAZMAT_NOTES { get; set; }
        public Nullable<decimal> GLD_WARRANTY { get; set; }
        public string IC_UDF_004A { get; set; }
        public Nullable<decimal> SAFETY_DAYS { get; set; }
        public Nullable<decimal> GLD_WO_FINISHED_GOODS { get; set; }
        public string AC_LEASE { get; set; }
        public Nullable<decimal> SHELF_LIFE_DAYS { get; set; }
        public Nullable<decimal> SMC_AUTO_KEY { get; set; }
        public string SMC_CODE { get; set; }
        public string MFG_FLAG { get; set; }
        public string OVHL_FLAG { get; set; }
        public string REPAIR_FLAG { get; set; }
        public string CERT_FLAG { get; set; }
        public string FIXED_ASSET { get; set; }
        public Nullable<decimal> GLA_ACCUM_DEPR { get; set; }
        public Nullable<decimal> GLA_DEPR_EXPENSE { get; set; }
        public Nullable<decimal> DPM_AUTO_KEY { get; set; }
        public Nullable<decimal> FAC_AUTO_KEY { get; set; }
        public string RAW_MATERIAL { get; set; }
        public string MFG_CAP_DESC { get; set; }
        public string OVHL_CAP_DESC { get; set; }
        public string REPAIR_CAP_DESC { get; set; }
        public string CERT_CAP_DESC { get; set; }
        public string MKT_PUBLISH_CAP { get; set; }
        public Nullable<decimal> MKT_STM_MFG { get; set; }
        public Nullable<decimal> MKT_STM_OVHL { get; set; }
        public Nullable<decimal> MKT_STM_REPAIR { get; set; }
        public Nullable<decimal> MKT_STM_CERT { get; set; }
        public string HOT_PART { get; set; }
        public string QB_LISTID { get; set; }
        public string SDF_PNM_001 { get; set; }
        public string SDF_PNM_002 { get; set; }
        public string SDF_PNM_003 { get; set; }
        public string SDF_PNM_004 { get; set; }
        public string SDF_PNM_005 { get; set; }
        public string SDF_PNM_006 { get; set; }
        public string SDF_PNM_007 { get; set; }
        public string SDF_PNM_008 { get; set; }
        public string SDF_PNM_009 { get; set; }
        public string SDF_PNM_010 { get; set; }
        public string HOLOGRAM { get; set; }
        public Nullable<decimal> MKC_AUTO_KEY { get; set; }
        public string MASTER_TOOL { get; set; }
        public string TOOL_TYPE { get; set; }
        public string TOOL_APPLICATION { get; set; }
        public Nullable<decimal> TOOL_FREQ { get; set; }
        public Nullable<decimal> PNU_AUTO_KEY { get; set; }
        public Nullable<decimal> ECON_ORD_QTY { get; set; }
        public string REQUIRES_REVIEW { get; set; }
        public Nullable<decimal> DEMAND_RATE { get; set; }
        public string PRIME { get; set; }
        public Nullable<decimal> BCC_AUTO_KEY { get; set; }
        public string REQ_VERIFICATION { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string CUSTOM_CODE { get; set; }
        public Nullable<decimal> CUSTOM_VALUE { get; set; }
        public Nullable<decimal> CUR_CUSTOMS { get; set; }
        public Nullable<decimal> COC_AUTO_KEY { get; set; }
        public string TOOL { get; set; }
        public string PO_TYPE { get; set; }
        public string DIST_FLAG { get; set; }
        public string DIST_CAP_DESC { get; set; }
        public Nullable<decimal> MKT_STM_DIST { get; set; }
        public string ACTIVITY { get; set; }
        public string IC_UDF_015 { get; set; }
        public string IC_UDF_016 { get; set; }
        public Nullable<decimal> TOTAL_INTERVALS { get; set; }
        public Nullable<decimal> FAP_AUTO_KEY { get; set; }
        public Nullable<decimal> EXP_DATE_TYPE { get; set; }
        public string IC_UDF_017 { get; set; }
        public string IC_UDF_018 { get; set; }
        public string IC_UDF_019 { get; set; }
        public string ALLOW_PRINT_8130 { get; set; }
        public string EDI_CHARGE_CODE { get; set; }
        public string TRACK_DELIVERY { get; set; }
        public string RECEIVER_INSTR { get; set; }
        public string TIME_LIFE { get; set; }
        public string ENQUEUE_MSG { get; set; }
        public Nullable<decimal> DISTR_PRICE { get; set; }
        public string AUTO_CALC_PRICELINES { get; set; }
        public string PROCUREMENT { get; set; }
        public Nullable<decimal> GLD_WIP_LABOR { get; set; }
        public Nullable<decimal> GLD_WIP_MISC { get; set; }
        public Nullable<decimal> GLD_WIP_REPAIR { get; set; }
        public Nullable<decimal> GLD_FG_LABOR { get; set; }
        public Nullable<decimal> GLD_FG_MISC { get; set; }
        public Nullable<decimal> GLD_FG_REPAIR { get; set; }
        public Nullable<decimal> GLD_COG_LABOR { get; set; }
        public Nullable<decimal> GLD_COG_MISC { get; set; }
        public Nullable<decimal> GLD_COG_REPAIR { get; set; }
        public Nullable<decimal> GLD_WIP_PARTS { get; set; }
        public Nullable<decimal> FAIR_MARKET_VALUE { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public string HAZ_MAT_ACCESS { get; set; }
        public string BYPASS_EM_INVOICE { get; set; }
        public string ECC { get; set; }
        public string ECC_NUMBER { get; set; }
        public string ITAR_NUMBER { get; set; }
        public Nullable<decimal> COC_MFG { get; set; }
        public Nullable<decimal> BPC_AUTO_KEY { get; set; }
        public Nullable<decimal> LEAD_DAYS_MFG { get; set; }
        public Nullable<decimal> DPT_AUTO_KEY { get; set; }
        public Nullable<decimal> PO_CORE_CHARGE { get; set; }
        public Nullable<decimal> LL_HOURS { get; set; }
        public Nullable<decimal> LL_CYCLES { get; set; }
        public Nullable<decimal> OH_HOURS { get; set; }
        public Nullable<decimal> OH_CYCLES { get; set; }
        public Nullable<decimal> INSP_HOURS { get; set; }
        public Nullable<decimal> INSP_CYCLES { get; set; }
        public string LL_CAL_TYPE { get; set; }
        public Nullable<decimal> LL_CAL_CNT { get; set; }
        public string OH_CAL_TYPE { get; set; }
        public Nullable<decimal> OH_CAL_CNT { get; set; }
        public string INSP_CAL_TYPE { get; set; }
        public Nullable<decimal> INSP_CAL_CNT { get; set; }
        public string SDF_PNM_011 { get; set; }
        public string SDF_PNM_012 { get; set; }
        public string SDF_PNM_013 { get; set; }
        public string SDF_PNM_014 { get; set; }
        public string SDF_PNM_015 { get; set; }
        public string SDF_PNM_016 { get; set; }
        public string SDF_PNM_017 { get; set; }
        public string SDF_PNM_018 { get; set; }
        public string SDF_PNM_019 { get; set; }
        public string SDF_PNM_020 { get; set; }
        public Nullable<decimal> QTY_MULTIPLIER { get; set; }
        public string CRITICAL { get; set; }
        public string EXCL_PO_REC_MARKUP { get; set; }
        public string NEVER_QUOTE_BILL { get; set; }
        public Nullable<decimal> BOM_MSRP { get; set; }
        public Nullable<System.DateTime> BOM_MSRP_DATE { get; set; }
        public string URL_LINK { get; set; }
        public string UNALLOWABLE { get; set; }
        public string MATERIAL_OVERHEAD { get; set; }
        public string BASE_LABOR { get; set; }
        public string OT_BASE_LABOR { get; set; }
        public string OT_LABOR { get; set; }
        public string ALLOW_PRINT_CAAC { get; set; }
        public string LENGTH { get; set; }
        public string WIDTH { get; set; }
        public string HEIGHT { get; set; }
        public Nullable<decimal> REORDER_COND_LEVEL { get; set; }
        public string BRIDGE_REFERENCE { get; set; }
        public Nullable<decimal> EQC_AUTO_KEY { get; set; }
        public string EXCHANGE_FLAG { get; set; }
        public Nullable<decimal> MKT_STM_EXCHANGE { get; set; }
        public string EXCHANGE_CAP_DESC { get; set; }
        public string URL_LINK_2 { get; set; }
        public string URL_LINK_3 { get; set; }
        public string URL_LINK_4 { get; set; }
        public string URL_LINK_5 { get; set; }
        public Nullable<decimal> PRN_AUTO_KEY { get; set; }
        public string IC_UDF_004_STRIPPED { get; set; }
        public string LIFE_LIMITED_PART { get; set; }
        public string SOURCE_MODULE { get; set; }
        public string TOOL_FREQ_TYPE { get; set; }
        public string DEFAULT_REMSTAR_BIN { get; set; }
        public string PMA_FLAG { get; set; }
        public Nullable<decimal> OPENED_SHELF_LIFE_DAYS { get; set; }
        public Nullable<decimal> PSR_AUTO_KEY { get; set; }
    
        public virtual ICollection<ALTERNATES_PARTS_MASTER> ALTERNATES_PARTS_MASTER { get; set; }
        public virtual ICollection<ALTERNATES_PARTS_MASTER> ALTERNATES_PARTS_MASTER1 { get; set; }
        public virtual ICollection<AP_DETAIL> AP_DETAIL { get; set; }
        public virtual APPLICATION_CODES APPLICATION_CODES { get; set; }
        public virtual ICollection<CQ_DETAIL> CQ_DETAIL { get; set; }
        public virtual ICollection<CQ_DETAIL> CQ_DETAIL1 { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<INVC_DETAIL> INVC_DETAIL { get; set; }
        public virtual ICollection<PART_APPLICATION_CODES> PART_APPLICATION_CODES { get; set; }
        public virtual PART_RANKING_NUMBERS PART_RANKING_NUMBERS { get; set; }
        public virtual ICollection<PART_SPECS> PART_SPECS { get; set; }
        public virtual ICollection<PARTS_CATALOG> PARTS_CATALOG { get; set; }
        public virtual ICollection<PO_DETAIL> PO_DETAIL { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL { get; set; }
        public virtual ICollection<PI_DETAIL> PI_DETAIL { get; set; }
        public virtual ICollection<PO_DETAIL> PO_DETAIL1 { get; set; }
        public virtual ICollection<PARTS_WHS_LOC> PARTS_WHS_LOC { get; set; }
        public virtual ICollection<RO_DETAIL> RO_DETAIL { get; set; }
        public virtual ICollection<RO_PRE_COSTING_CHARGES> RO_PRE_COSTING_CHARGES { get; set; }
        public virtual ICollection<RO_PIECE_PARTS> RO_PIECE_PARTS { get; set; }
        public virtual ICollection<SM_DETAIL> SM_DETAIL { get; set; }
        public virtual ICollection<SM_HISTORY> SM_HISTORY { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL1 { get; set; }
        public virtual ICollection<STOCK> STOCKs { get; set; }
        public virtual ICollection<RC_DETAIL> RC_DETAIL { get; set; }
        public virtual ICollection<RC_DETAIL> RC_DETAIL1 { get; set; }
        public virtual STOCK_CATEGORY_CODES STOCK_CATEGORY_CODES { get; set; }
        public virtual ICollection<RO_DETAIL> RO_DETAIL1 { get; set; }
    }
}
