//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_RANKING_NUMBERS
    {
        public PART_RANKING_NUMBERS()
        {
            this.PARTS_MASTER = new HashSet<PARTS_MASTER>();
        }
    
        public decimal PRN_AUTO_KEY { get; set; }
        public decimal RANKING_NUMBER { get; set; }
        public string CATEGORY_CODE { get; set; }
        public string RANKING_GROUP { get; set; }
    
        public virtual ICollection<PARTS_MASTER> PARTS_MASTER { get; set; }
    }
}
