//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_APPLICATION_CODES
    {
        public decimal PAC_AUTO_KEY { get; set; }
        public decimal PNM_AUTO_KEY { get; set; }
        public decimal APC_AUTO_KEY { get; set; }
        public string CONVERTED { get; set; }
        public string SDF_PAC_001 { get; set; }
        public string SDF_PAC_002 { get; set; }
        public string SDF_PAC_003 { get; set; }
        public string SDF_PAC_004 { get; set; }
        public string SDF_PAC_005 { get; set; }
        public string SDF_PAC_006 { get; set; }
        public string SDF_PAC_007 { get; set; }
        public string SDF_PAC_008 { get; set; }
        public string SDF_PAC_009 { get; set; }
        public string SDF_PAC_010 { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public string UDF_PAC_001 { get; set; }
        public string UDF_PAC_002 { get; set; }
        public string UDF_PAC_003 { get; set; }
        public string UDF_PAC_004 { get; set; }
        public string UDF_PAC_005 { get; set; }
        public string UDF_PAC_006 { get; set; }
        public string UDF_PAC_007 { get; set; }
        public string UDF_PAC_008 { get; set; }
        public string UDF_PAC_009 { get; set; }
        public string UDF_PAC_010 { get; set; }
    
        public virtual APPLICATION_CODES APPLICATION_CODES { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER { get; set; }
    }
}
