//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_DETAIL
    {
        public decimal PID_AUTO_KEY { get; set; }
        public decimal PIH_AUTO_KEY { get; set; }
        public decimal PNM_AUTO_KEY { get; set; }
        public decimal WHS_AUTO_KEY { get; set; }
        public decimal LOC_AUTO_KEY { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> QTY_FOUND { get; set; }
        public string NOTES { get; set; }
        public string RESOLVED { get; set; }
        public Nullable<decimal> STM_AUTO_KEY { get; set; }
        public Nullable<decimal> CTRL_NUMBER { get; set; }
        public Nullable<decimal> CTRL_ID { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public Nullable<decimal> PCC_AUTO_KEY { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> QTY_RESERVED { get; set; }
        public string SORT_FIELD { get; set; }
        public string MANUALLY_ADDED { get; set; }
        public string SDF_PID_001 { get; set; }
        public string SDF_PID_002 { get; set; }
        public string SDF_PID_003 { get; set; }
        public string SDF_PID_004 { get; set; }
        public string SDF_PID_005 { get; set; }
        public string SDF_PID_006 { get; set; }
        public string SDF_PID_007 { get; set; }
        public string SDF_PID_008 { get; set; }
        public string SDF_PID_009 { get; set; }
        public string SDF_PID_010 { get; set; }
        public string POSTED { get; set; }
        public Nullable<System.DateTime> POST_DATE { get; set; }
        public Nullable<decimal> SAJ_AUTO_KEY { get; set; }
    
        public virtual PARTS_MASTER PARTS_MASTER { get; set; }
        public virtual PI_HEADER PI_HEADER { get; set; }
    }
}
