//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_HEADER
    {
        public PI_HEADER()
        {
            this.PI_DETAIL = new HashSet<PI_DETAIL>();
        }
    
        public decimal PIH_AUTO_KEY { get; set; }
        public string PI_NUMBER { get; set; }
        public Nullable<decimal> PIS_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string OPEN_FLAG { get; set; }
        public string NOTES { get; set; }
        public decimal GEO_AUTO_KEY { get; set; }
        public Nullable<decimal> WHS_AUTO_KEY { get; set; }
        public Nullable<decimal> LOC_FROM { get; set; }
        public Nullable<decimal> LOC_TO { get; set; }
        public Nullable<decimal> COUNT_LEVEL { get; set; }
        public string COUNT_SOD_RES { get; set; }
        public string COUNT_WOB_RES { get; set; }
        public string COUNT_POD_RES { get; set; }
        public string COUNT_ROD_RES { get; set; }
        public string COUNT_RPP_RES { get; set; }
        public string COUNT_WOO_RES { get; set; }
        public string TRACK_CHANGES { get; set; }
        public string SDF_PIH_001 { get; set; }
        public string SDF_PIH_002 { get; set; }
        public string SDF_PIH_003 { get; set; }
        public string SDF_PIH_004 { get; set; }
        public string SDF_PIH_005 { get; set; }
        public string SDF_PIH_006 { get; set; }
        public string SDF_PIH_007 { get; set; }
        public string SDF_PIH_008 { get; set; }
        public string SDF_PIH_009 { get; set; }
        public string SDF_PIH_010 { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public string COUNT_PPP_RES { get; set; }
    
        public virtual ICollection<PI_DETAIL> PI_DETAIL { get; set; }
        public virtual PI_STATUS PI_STATUS { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
