//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuantumEntities : DbContext
    {
        public QuantumEntities()
            : base("name=QuantumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AC_CONTROL> AC_CONTROL { get; set; }
        public DbSet<AC_STATUS_TYPE> AC_STATUS_TYPE { get; set; }
        public DbSet<AGENT> AGENTS { get; set; }
        public DbSet<ALTERNATE_TYPE_CODES> ALTERNATE_TYPE_CODES { get; set; }
        public DbSet<ALTERNATES_PARTS_MASTER> ALTERNATES_PARTS_MASTER { get; set; }
        public DbSet<AP_ACCOUNT> AP_ACCOUNT { get; set; }
        public DbSet<AP_DETAIL> AP_DETAIL { get; set; }
        public DbSet<APPLICATION_CODES> APPLICATION_CODES { get; set; }
        public DbSet<AR_ACCOUNT> AR_ACCOUNT { get; set; }
        public DbSet<AR_DETAIL> AR_DETAIL { get; set; }
        public DbSet<COMMISSION_CODES> COMMISSION_CODES { get; set; }
        public DbSet<COMPANy> COMPANIES { get; set; }
        public DbSet<COMPANY_AGENTS> COMPANY_AGENTS { get; set; }
        public DbSet<COMPANY_LIST> COMPANY_LIST { get; set; }
        public DbSet<CQ_DETAIL> CQ_DETAIL { get; set; }
        public DbSet<CQ_HEADER> CQ_HEADER { get; set; }
        public DbSet<CQ_STATUS> CQ_STATUS { get; set; }
        public DbSet<CURRENCY> CURRENCies { get; set; }
        public DbSet<CUSTOMER_DISCOUNT_CODES> CUSTOMER_DISCOUNT_CODES { get; set; }
        public DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public DbSet<INVC_DETAIL> INVC_DETAIL { get; set; }
        public DbSet<INVC_HEADER> INVC_HEADER { get; set; }
        public DbSet<PART_APPLICATION_CODES> PART_APPLICATION_CODES { get; set; }
        public DbSet<PART_CONDITION_CODES> PART_CONDITION_CODES { get; set; }
        public DbSet<PART_RANKING_NUMBERS> PART_RANKING_NUMBERS { get; set; }
        public DbSet<PART_SPECS> PART_SPECS { get; set; }
        public DbSet<PARTS_CATALOG> PARTS_CATALOG { get; set; }
        public DbSet<PARTS_MASTER> PARTS_MASTER { get; set; }
        public DbSet<PARTS_WHS_LOC> PARTS_WHS_LOC { get; set; }
        public DbSet<PI_DETAIL> PI_DETAIL { get; set; }
        public DbSet<PI_HEADER> PI_HEADER { get; set; }
        public DbSet<PI_STATUS> PI_STATUS { get; set; }
        public DbSet<PO_CATEGORY_CODES> PO_CATEGORY_CODES { get; set; }
        public DbSet<PO_DETAIL> PO_DETAIL { get; set; }
        public DbSet<PO_HEADER> PO_HEADER { get; set; }
        public DbSet<PO_STATUS> PO_STATUS { get; set; }
        public DbSet<RC_DETAIL> RC_DETAIL { get; set; }
        public DbSet<RC_DISP_CODES> RC_DISP_CODES { get; set; }
        public DbSet<RC_HEADER> RC_HEADER { get; set; }
        public DbSet<RC_SERIAL> RC_SERIAL { get; set; }
        public DbSet<RC_STATUS> RC_STATUS { get; set; }
        public DbSet<RO_CATEGORY_CODES> RO_CATEGORY_CODES { get; set; }
        public DbSet<RO_CONTROL> RO_CONTROL { get; set; }
        public DbSet<RO_DETAIL> RO_DETAIL { get; set; }
        public DbSet<RO_HEADER> RO_HEADER { get; set; }
        public DbSet<RO_PIECE_PARTS> RO_PIECE_PARTS { get; set; }
        public DbSet<RO_PRE_COSTING_CHARGES> RO_PRE_COSTING_CHARGES { get; set; }
        public DbSet<RO_STATUS> RO_STATUS { get; set; }
        public DbSet<SM_DETAIL> SM_DETAIL { get; set; }
        public DbSet<SM_HEADER> SM_HEADER { get; set; }
        public DbSet<SM_HISTORY> SM_HISTORY { get; set; }
        public DbSet<SM_STATUS> SM_STATUS { get; set; }
        public DbSet<SO_CATEGORY_CODES> SO_CATEGORY_CODES { get; set; }
        public DbSet<SO_DETAIL> SO_DETAIL { get; set; }
        public DbSet<SO_HEADER> SO_HEADER { get; set; }
        public DbSet<SO_STATUS> SO_STATUS { get; set; }
        public DbSet<STOCK> STOCKs { get; set; }
        public DbSet<STOCK_CATEGORY_CODES> STOCK_CATEGORY_CODES { get; set; }
        public DbSet<STOCK_RESERVATIONS> STOCK_RESERVATIONS { get; set; }
        public DbSet<SYS_USERS> SYS_USERS { get; set; }
        public DbSet<RO_SALES> RO_SALES { get; set; }
    }
}
