//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RC_DISP_CODES
    {
        public RC_DISP_CODES()
        {
            this.RC_SERIAL = new HashSet<RC_SERIAL>();
        }
    
        public decimal RDC_AUTO_KEY { get; set; }
        public string DISP_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string SDF_RDC_001 { get; set; }
        public string SDF_RDC_002 { get; set; }
        public string SDF_RDC_003 { get; set; }
        public string SDF_RDC_004 { get; set; }
        public string SDF_RDC_005 { get; set; }
        public string SDF_RDC_006 { get; set; }
        public string SDF_RDC_007 { get; set; }
        public string SDF_RDC_008 { get; set; }
        public string SDF_RDC_009 { get; set; }
        public string SDF_RDC_010 { get; set; }
    
        public virtual ICollection<RC_SERIAL> RC_SERIAL { get; set; }
    }
}
