//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RC_HEADER
    {
        public RC_HEADER()
        {
            this.RC_DETAIL = new HashSet<RC_DETAIL>();
        }
    
        public decimal RCH_AUTO_KEY { get; set; }
        public Nullable<decimal> CMP_AUTO_KEY { get; set; }
        public Nullable<decimal> POH_AUTO_KEY { get; set; }
        public Nullable<decimal> ROH_AUTO_KEY { get; set; }
        public Nullable<decimal> INH_AUTO_KEY { get; set; }
        public Nullable<decimal> SOH_AUTO_KEY { get; set; }
        public Nullable<decimal> WOO_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSCM_AUTO_KEY { get; set; }
        public Nullable<decimal> DPT_AUTO_KEY { get; set; }
        public string RC_NUMBER { get; set; }
        public string COMPANY_NAME { get; set; }
        public string ORDER_NUMBER1 { get; set; }
        public string ORDER_TYPE1 { get; set; }
        public string ORDER_NUMBER2 { get; set; }
        public string ORDER_TYPE2 { get; set; }
        public string NOTES { get; set; }
        public string OPEN_FLAG { get; set; }
        public Nullable<decimal> REC_TRAN_ID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string CREDIT_INVC_NUMBER { get; set; }
        public Nullable<decimal> MXH_AUTO_KEY { get; set; }
        public string SHIP_INVC_NUMBER { get; set; }
        public Nullable<decimal> SHIP_CMP { get; set; }
        public string SHIPMENT_NUMBER { get; set; }
        public string SDF_RCH_001 { get; set; }
        public string SDF_RCH_002 { get; set; }
        public string SDF_RCH_003 { get; set; }
        public string SDF_RCH_004 { get; set; }
        public string SDF_RCH_005 { get; set; }
        public string SDF_RCH_006 { get; set; }
        public string SDF_RCH_007 { get; set; }
        public string SDF_RCH_008 { get; set; }
        public string SDF_RCH_009 { get; set; }
        public string SDF_RCH_010 { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public string AIRWAY_BILL { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_CONVERTED { get; set; }
        public Nullable<decimal> SMH_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public string UDF_RCH_001 { get; set; }
        public string UDF_RCH_002 { get; set; }
        public string UDF_RCH_003 { get; set; }
        public Nullable<System.DateTime> ARRIVAL_DATE { get; set; }
        public Nullable<decimal> LOC_AUTO_KEY { get; set; }
        public Nullable<decimal> CUSTOMS_STATUS { get; set; }
        public string SDF_RCH_011 { get; set; }
        public string SDF_RCH_012 { get; set; }
        public string SDF_RCH_013 { get; set; }
        public string SDF_RCH_014 { get; set; }
        public string SDF_RCH_015 { get; set; }
        public string SDF_RCH_016 { get; set; }
        public string SDF_RCH_017 { get; set; }
        public string SDF_RCH_018 { get; set; }
        public string SDF_RCH_019 { get; set; }
        public string SDF_RCH_020 { get; set; }
        public string SDF_RCH_021 { get; set; }
        public string SDF_RCH_022 { get; set; }
        public string SDF_RCH_023 { get; set; }
        public string SDF_RCH_024 { get; set; }
        public string SDF_RCH_025 { get; set; }
        public string SDF_RCH_026 { get; set; }
        public string SDF_RCH_027 { get; set; }
        public string SDF_RCH_028 { get; set; }
        public string SDF_RCH_029 { get; set; }
        public string SDF_RCH_030 { get; set; }
        public Nullable<decimal> CSS_AUTO_KEY { get; set; }
        public Nullable<decimal> COC_ORIGIN { get; set; }
        public Nullable<decimal> WCH_AUTO_KEY { get; set; }
    
        public virtual COMPANy COMPANy { get; set; }
        public virtual COMPANy COMPANy1 { get; set; }
        public virtual ICollection<RC_DETAIL> RC_DETAIL { get; set; }
    }
}
