//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RC_STATUS
    {
        public RC_STATUS()
        {
            this.RC_DETAIL = new HashSet<RC_DETAIL>();
            this.RC_SERIAL = new HashSet<RC_SERIAL>();
        }
    
        public decimal RCS_AUTO_KEY { get; set; }
        public string STATUS_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUS_TYPE { get; set; }
        public string SDF_RCS_001 { get; set; }
        public string SDF_RCS_002 { get; set; }
        public string SDF_RCS_003 { get; set; }
        public string SDF_RCS_004 { get; set; }
        public string SDF_RCS_005 { get; set; }
        public string SDF_RCS_006 { get; set; }
        public string SDF_RCS_007 { get; set; }
        public string SDF_RCS_008 { get; set; }
        public string SDF_RCS_009 { get; set; }
        public string SDF_RCS_010 { get; set; }
    
        public virtual ICollection<RC_DETAIL> RC_DETAIL { get; set; }
        public virtual ICollection<RC_SERIAL> RC_SERIAL { get; set; }
    }
}
