//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RC_SERIAL
    {
        public decimal RCL_AUTO_KEY { get; set; }
        public decimal RCD_AUTO_KEY { get; set; }
        public decimal RCS_AUTO_KEY { get; set; }
        public decimal RDC_AUTO_KEY { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string PART_CERT_NUMBER { get; set; }
        public string TAGGED_BY { get; set; }
        public Nullable<System.DateTime> TAG_DATE { get; set; }
        public string TRACK_LIFE { get; set; }
        public Nullable<decimal> TIME_SINCE_NEW { get; set; }
        public Nullable<decimal> TIME_SINCE_OVHL { get; set; }
        public Nullable<decimal> TIME_REM { get; set; }
        public Nullable<decimal> CYCLE_SINCE_NEW { get; set; }
        public Nullable<decimal> CYCLE_SINCE_OVHL { get; set; }
        public Nullable<decimal> CYCLE_REM { get; set; }
        public string LIFE_ORIGIN { get; set; }
        public string LIFE_REMARKS { get; set; }
        public Nullable<decimal> SERIES_NUMBER { get; set; }
        public Nullable<decimal> SERIES_ID { get; set; }
        public Nullable<decimal> CTRL_NUMBER { get; set; }
        public Nullable<decimal> CTRL_ID { get; set; }
        public string RECEIVED { get; set; }
        public Nullable<decimal> REC_TRAN_ID { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> STM_ORIGINAL { get; set; }
        public string VISIBLE_MKT { get; set; }
        public string SDF_RCL_001 { get; set; }
        public string SDF_RCL_002 { get; set; }
        public string SDF_RCL_003 { get; set; }
        public string SDF_RCL_004 { get; set; }
        public string SDF_RCL_005 { get; set; }
        public string SDF_RCL_006 { get; set; }
        public string SDF_RCL_007 { get; set; }
        public string SDF_RCL_008 { get; set; }
        public string SDF_RCL_009 { get; set; }
        public string SDF_RCL_010 { get; set; }
        public string HOLOGRAM_NUMBER { get; set; }
        public Nullable<decimal> TIME_SINCE_REPAIR { get; set; }
        public Nullable<decimal> CYCLE_SINCE_REPAIR { get; set; }
        public Nullable<System.DateTime> INSPECT_DUE_DATE { get; set; }
        public Nullable<decimal> TIME_SINCE_INSP { get; set; }
        public Nullable<decimal> CYCLE_SINCE_INSP { get; set; }
        public Nullable<System.DateTime> MFG_DATE { get; set; }
        public Nullable<System.DateTime> LAST_OVHL { get; set; }
        public Nullable<System.DateTime> LAST_INSP { get; set; }
        public string UNKNOWN_LIFE { get; set; }
        public Nullable<System.DateTime> EXP_DATE { get; set; }
        public string ASSET_NUMBER { get; set; }
        public string TAG_NUMBER { get; set; }
        public string SIGN_OFF_FLAG { get; set; }
        public Nullable<decimal> SYSUR_SIGN_OFF { get; set; }
        public Nullable<decimal> EIT_AUTO_KEY { get; set; }
        public Nullable<decimal> TTP_AUTO_KEY { get; set; }
    
        public virtual RC_DETAIL RC_DETAIL { get; set; }
        public virtual RC_DISP_CODES RC_DISP_CODES { get; set; }
        public virtual RC_STATUS RC_STATUS { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
