//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RO_CATEGORY_CODES
    {
        public RO_CATEGORY_CODES()
        {
            this.RO_DETAIL = new HashSet<RO_DETAIL>();
            this.RO_HEADER = new HashSet<RO_HEADER>();
        }
    
        public decimal RCT_AUTO_KEY { get; set; }
        public string RO_CATEGORY_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal SEQUENCE { get; set; }
        public string SDF_RCT_001 { get; set; }
        public string SDF_RCT_002 { get; set; }
        public string SDF_RCT_003 { get; set; }
        public string SDF_RCT_004 { get; set; }
        public string SDF_RCT_005 { get; set; }
        public string SDF_RCT_006 { get; set; }
        public string SDF_RCT_007 { get; set; }
        public string SDF_RCT_008 { get; set; }
        public string SDF_RCT_009 { get; set; }
        public string SDF_RCT_010 { get; set; }
    
        public virtual ICollection<RO_DETAIL> RO_DETAIL { get; set; }
        public virtual ICollection<RO_HEADER> RO_HEADER { get; set; }
    }
}
