//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RO_CONTROL
    {
        public decimal ROC_AUTO_KEY { get; set; }
        public string AUTO_LINK_CM { get; set; }
        public Nullable<decimal> PJS_SM_ROD { get; set; }
        public Nullable<decimal> PJS_SM_CLOSED { get; set; }
        public Nullable<decimal> PJS_RECEIVED { get; set; }
        public string AUTO_CM_STATUS { get; set; }
        public Nullable<decimal> PJS_LINKED { get; set; }
        public string COPY_ADDR_FROM_WO_MAIN { get; set; }
        public string VEND_INV_METHOD { get; set; }
        public string PROMPT_SER_HIST { get; set; }
        public Nullable<decimal> RST_NEW { get; set; }
        public Nullable<decimal> RST_CLOSED { get; set; }
        public string CAPITALIZE_RO_COST_FOR_EXC { get; set; }
    }
}
