//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RO_DETAIL
    {
        public RO_DETAIL()
        {
            this.RC_DETAIL = new HashSet<RC_DETAIL>();
            this.RO_PIECE_PARTS = new HashSet<RO_PIECE_PARTS>();
            this.SM_DETAIL = new HashSet<SM_DETAIL>();
            this.SO_DETAIL = new HashSet<SO_DETAIL>();
            this.STOCKs = new HashSet<STOCK>();
            this.STOCK_RESERVATIONS = new HashSet<STOCK_RESERVATIONS>();
        }
    
        public decimal ROD_AUTO_KEY { get; set; }
        public Nullable<decimal> SOD_AUTO_KEY { get; set; }
        public Nullable<decimal> PNM_AUTO_KEY { get; set; }
        public Nullable<decimal> PCC_AUTO_KEY { get; set; }
        public Nullable<decimal> ROH_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public decimal ITEM_NUMBER { get; set; }
        public Nullable<decimal> LABOR_COST { get; set; }
        public Nullable<System.DateTime> LAST_DELIVERY_DATE { get; set; }
        public Nullable<decimal> MISC_COST { get; set; }
        public Nullable<System.DateTime> NEXT_DELIVERY_DATE { get; set; }
        public Nullable<decimal> PARTS_COST { get; set; }
        public string REPAIR_NOTES { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<decimal> QTY_REPAIR { get; set; }
        public Nullable<decimal> QTY_RESERVED { get; set; }
        public Nullable<decimal> QTY_REPAIRED { get; set; }
        public Nullable<decimal> QTY_SCRAPPED { get; set; }
        public Nullable<decimal> PNM_MODIFY { get; set; }
        public string CLOSED_UPDATE { get; set; }
        public Nullable<decimal> FOREIGN_LABOR { get; set; }
        public Nullable<decimal> FOREIGN_MISC { get; set; }
        public Nullable<decimal> FOREIGN_PARTS { get; set; }
        public Nullable<decimal> QTY_SCRAP_LINE { get; set; }
        public string BILLED_LEASE { get; set; }
        public Nullable<decimal> WOB_AUTO_KEY { get; set; }
        public Nullable<decimal> WOO_AUTO_KEY { get; set; }
        public Nullable<decimal> QTY_BILLED { get; set; }
        public string CQD_LINK { get; set; }
        public string HAS_PIECE_PARTS { get; set; }
        public string SMD_LINK { get; set; }
        public Nullable<decimal> WO_PRICE { get; set; }
        public string CONVERTED { get; set; }
        public string RECEIVER_INSTR { get; set; }
        public string VEND_INV_METHOD { get; set; }
        public string BILL_FOR_OVERRUN { get; set; }
        public Nullable<decimal> CAPITALIZE_COST { get; set; }
        public Nullable<decimal> EXPENSE_COST { get; set; }
        public string EXT_AP_NUMBER { get; set; }
        public Nullable<System.DateTime> EXT_AP_DATE { get; set; }
        public Nullable<decimal> FOREIGN_EXP_COST { get; set; }
        public Nullable<decimal> FOREIGN_CAP_COST { get; set; }
        public Nullable<decimal> VENDOR_ADJ { get; set; }
        public Nullable<decimal> FOREIGN_VEND_ADJ { get; set; }
        public Nullable<decimal> PNM_CHARGE { get; set; }
        public string PRINT_PICKTICKET_FLAG { get; set; }
        public string ROUTE_CODE { get; set; }
        public string ROUTE_DESC { get; set; }
        public Nullable<decimal> WOT_AUTO_KEY { get; set; }
        public Nullable<decimal> ELC_AUTO_KEY { get; set; }
        public string SDF_ROD_001 { get; set; }
        public string SDF_ROD_002 { get; set; }
        public string SDF_ROD_003 { get; set; }
        public string SDF_ROD_004 { get; set; }
        public string SDF_ROD_005 { get; set; }
        public string SDF_ROD_006 { get; set; }
        public string SDF_ROD_007 { get; set; }
        public string SDF_ROD_008 { get; set; }
        public string SDF_ROD_009 { get; set; }
        public string SDF_ROD_010 { get; set; }
        public Nullable<decimal> EST_PRICE { get; set; }
        public string QB_WO_MC_TRAN { get; set; }
        public Nullable<decimal> QB_QTY_REPAIRED { get; set; }
        public Nullable<decimal> QB_QTY_SCRAPPED { get; set; }
        public Nullable<decimal> QB_PARTS_COST { get; set; }
        public Nullable<decimal> QB_LABOR_COST { get; set; }
        public Nullable<decimal> QB_MISC_COST { get; set; }
        public string FLAT_RATE { get; set; }
        public Nullable<decimal> QTY_REC_INCR { get; set; }
        public Nullable<decimal> REC_TRAN_ID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED { get; set; }
        public Nullable<decimal> SYSUR_MODIFIED { get; set; }
        public Nullable<decimal> PRE_TAX_PARTS_COST { get; set; }
        public Nullable<decimal> PRE_TAX_LABOR_COST { get; set; }
        public Nullable<decimal> PRE_TAX_MISC_COST { get; set; }
        public Nullable<decimal> PRE_TAX_FGN_PARTS_COST { get; set; }
        public Nullable<decimal> PRE_TAX_FGN_LABOR_COST { get; set; }
        public Nullable<decimal> PRE_TAX_FGN_MISC_COST { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public Nullable<decimal> FOREIGN_TAX_AMOUNT { get; set; }
        public string CALC_TAX { get; set; }
        public Nullable<decimal> RCT_AUTO_KEY { get; set; }
        public string CALIBRATION_FLAG { get; set; }
        public Nullable<decimal> COC_AUTO_KEY { get; set; }
        public Nullable<decimal> APC_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> COMMIT_SHIP_DATE { get; set; }
        public Nullable<decimal> PRI_AUTO_KEY { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public string SHOP_FINDINGS { get; set; }
        public string FINAL_REMARKS { get; set; }
        public Nullable<System.DateTime> RO_UDF_001 { get; set; }
        public Nullable<System.DateTime> RO_UDF_002 { get; set; }
        public Nullable<System.DateTime> RO_UDF_003 { get; set; }
        public string ECC { get; set; }
        public Nullable<System.DateTime> RO_UDF_004 { get; set; }
        public Nullable<System.DateTime> MSG_RFQ_SENT_DATE { get; set; }
        public Nullable<System.DateTime> MSG_QUOTE_REC_DATE { get; set; }
        public Nullable<System.DateTime> MSG_QUOTE_APPR_DATE { get; set; }
        public Nullable<System.DateTime> MSG_QUOTE_REJECT_DATE { get; set; }
        public Nullable<System.DateTime> MSG_RO_SHIP_DATE { get; set; }
        public Nullable<System.DateTime> MSG_VEND_ACK_DATE { get; set; }
        public Nullable<System.DateTime> MSG_EST_DELIV_DATE { get; set; }
        public Nullable<System.DateTime> MSG_SHIP_NOTICE_DATE { get; set; }
        public Nullable<decimal> QUOTED_PARTS_FOREIGN { get; set; }
        public Nullable<decimal> QUOTED_PARTS_HOME { get; set; }
        public Nullable<decimal> QUOTED_LABOR_FOREIGN { get; set; }
        public Nullable<decimal> QUOTED_LABOR_HOME { get; set; }
        public Nullable<decimal> QUOTED_MISC_FOREIGN { get; set; }
        public Nullable<decimal> QUOTED_MISC_HOME { get; set; }
        public string QQM_MSG_GUID { get; set; }
        public Nullable<decimal> MSG_RFQ_SENT_CNT { get; set; }
        public Nullable<decimal> MSG_QUOTE_REC_CNT { get; set; }
        public Nullable<decimal> MSG_QUOTE_APPR_CNT { get; set; }
        public Nullable<decimal> MSG_QUOTE_REJECT_CNT { get; set; }
        public Nullable<decimal> MSG_RO_SHIP_CNT { get; set; }
        public Nullable<decimal> MSG_VEND_ACK_CNT { get; set; }
        public Nullable<decimal> MSG_EST_DELIV_CNT { get; set; }
        public Nullable<decimal> MSG_SHIP_NOTICE_CNT { get; set; }
        public string MSG_AIRWAY_BILL { get; set; }
        public string MSG_SHIP_VIA_CODE { get; set; }
        public string RO_TYPE { get; set; }
        public Nullable<decimal> RECEIVED_FOREIGN_PARTS { get; set; }
        public Nullable<decimal> RECEIVED_FOREIGN_LABOR { get; set; }
        public Nullable<decimal> RECEIVED_FOREIGN_MISC { get; set; }
        public Nullable<decimal> STC_AUTO_KEY { get; set; }
        public string SKIP_RR_FLAG { get; set; }
        public string SDF_ROD_011 { get; set; }
        public string SDF_ROD_012 { get; set; }
        public string SDF_ROD_013 { get; set; }
        public string SDF_ROD_014 { get; set; }
        public string SDF_ROD_015 { get; set; }
        public string SDF_ROD_016 { get; set; }
        public string SDF_ROD_017 { get; set; }
        public string SDF_ROD_018 { get; set; }
        public string SDF_ROD_019 { get; set; }
        public string SDF_ROD_020 { get; set; }
        public Nullable<System.DateTime> MSG_QUOTE_AUTO_APPR_DATE { get; set; }
        public Nullable<decimal> CAP_AUTO_KEY { get; set; }
        public Nullable<decimal> CTH_AUTO_KEY { get; set; }
        public Nullable<decimal> CIM_AUTO_KEY { get; set; }
        public Nullable<decimal> CEM_AUTO_KEY { get; set; }
        public Nullable<decimal> GROUP_NUMBER { get; set; }
        public Nullable<decimal> ROD_SPLIT_FROM { get; set; }
        public Nullable<decimal> RECEIVED_LABOR_COST { get; set; }
        public Nullable<decimal> RECEIVED_MISC_COST { get; set; }
        public Nullable<decimal> RECEIVED_PARTS_COST { get; set; }
        public Nullable<decimal> RECEIVED_EXCHANGE_RATE { get; set; }
    
        public virtual APPLICATION_CODES APPLICATION_CODES { get; set; }
        public virtual PART_CONDITION_CODES PART_CONDITION_CODES { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER1 { get; set; }
        public virtual ICollection<RC_DETAIL> RC_DETAIL { get; set; }
        public virtual RO_CATEGORY_CODES RO_CATEGORY_CODES { get; set; }
        public virtual ICollection<RO_PIECE_PARTS> RO_PIECE_PARTS { get; set; }
        public virtual ICollection<SM_DETAIL> SM_DETAIL { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL { get; set; }
        public virtual ICollection<STOCK> STOCKs { get; set; }
        public virtual ICollection<STOCK_RESERVATIONS> STOCK_RESERVATIONS { get; set; }
        public virtual RO_HEADER RO_HEADER { get; set; }
        public virtual SO_DETAIL SO_DETAIL1 { get; set; }
        public virtual STOCK_CATEGORY_CODES STOCK_CATEGORY_CODES { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
