//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RO_HEADER
    {
        public RO_HEADER()
        {
            this.AP_DETAIL = new HashSet<AP_DETAIL>();
            this.RO_DETAIL = new HashSet<RO_DETAIL>();
            this.RO_PRE_COSTING_CHARGES = new HashSet<RO_PRE_COSTING_CHARGES>();
            this.SM_HEADER = new HashSet<SM_HEADER>();
        }
    
        public decimal ROH_AUTO_KEY { get; set; }
        public string RO_NUMBER { get; set; }
        public decimal CMP_AUTO_KEY { get; set; }
        public Nullable<decimal> CUR_AUTO_KEY { get; set; }
        public Nullable<decimal> SVC_AUTO_KEY { get; set; }
        public Nullable<decimal> TMC_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string FAX_NUMBER { get; set; }
        public string HISTORICAL_FLAG { get; set; }
        public string IN_OUT_FLAG { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> NUMBER_OF_ITEMS { get; set; }
        public Nullable<decimal> TOTAL_COST { get; set; }
        public string OPEN_FLAG { get; set; }
        public string OVHL_STATION { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string RESALE_FLAG { get; set; }
        public string SHIP_ADDRESS1 { get; set; }
        public string SHIP_ADDRESS2 { get; set; }
        public string SHIP_ADDRESS3 { get; set; }
        public string SHIP_ADDRESS4 { get; set; }
        public string SHIP_ADDRESS5 { get; set; }
        public string SHIP_NAME { get; set; }
        public string ATTENTION { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> OUT_DATE { get; set; }
        public string FOB { get; set; }
        public string CLOSED_UPDATE { get; set; }
        public Nullable<decimal> SYSCM_AUTO_KEY { get; set; }
        public Nullable<decimal> DPT_AUTO_KEY { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string WARRANTY_FLAG { get; set; }
        public Nullable<System.DateTime> REPLY_DATE { get; set; }
        public Nullable<System.DateTime> COMMIT_SHIP_DATE { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string CONVERTED { get; set; }
        public Nullable<System.DateTime> QUOTE_DATE { get; set; }
        public string EXT_AP_NUMBER { get; set; }
        public Nullable<System.DateTime> EXT_AP_DATE { get; set; }
        public Nullable<decimal> EXT_AP_AMOUNT { get; set; }
        public Nullable<System.DateTime> NEXT_ACT_DATE { get; set; }
        public string TRACK_CHANGES { get; set; }
        public Nullable<decimal> SVA_AUTO_KEY { get; set; }
        public string VENDOR_NAME { get; set; }
        public string VENDOR_ADDRESS1 { get; set; }
        public string VENDOR_ADDRESS2 { get; set; }
        public string VENDOR_ADDRESS3 { get; set; }
        public string VENDOR_ADDRESS4 { get; set; }
        public string VENDOR_ADDRESS5 { get; set; }
        public Nullable<decimal> CST_AUTO_KEY { get; set; }
        public Nullable<decimal> APA_AUTO_KEY { get; set; }
        public string DEFERRED_REC { get; set; }
        public string TRACKING_NUMBER { get; set; }
        public string COMPANY_REF_NUMBER { get; set; }
        public Nullable<decimal> USR_AUTO_KEY { get; set; }
        public string SDF_ROH_001 { get; set; }
        public string SDF_ROH_002 { get; set; }
        public string SDF_ROH_003 { get; set; }
        public string SDF_ROH_004 { get; set; }
        public string SDF_ROH_005 { get; set; }
        public string SDF_ROH_006 { get; set; }
        public string SDF_ROH_007 { get; set; }
        public string SDF_ROH_008 { get; set; }
        public string SDF_ROH_009 { get; set; }
        public string SDF_ROH_010 { get; set; }
        public Nullable<decimal> COC_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED { get; set; }
        public Nullable<decimal> SYSUR_MODIFIED { get; set; }
        public string PROC_CODE { get; set; }
        public string HOLD_CODE { get; set; }
        public string BATCH_NUMBER { get; set; }
        public string EXPEDITE_FLAG { get; set; }
        public Nullable<decimal> ACT_AUTO_KEY { get; set; }
        public Nullable<decimal> MSG_AK_PO_REQ { get; set; }
        public Nullable<System.DateTime> PO_REQ_SENT { get; set; }
        public Nullable<decimal> MSG_AK_PO_CHGORD { get; set; }
        public Nullable<System.DateTime> PO_CHGORD_SENT { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<decimal> SYSUR_REQUESTED { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public Nullable<decimal> SHIP_PRIORITY { get; set; }
        public string RECO { get; set; }
        public string URL_LINK { get; set; }
        public Nullable<decimal> RST_AUTO_KEY { get; set; }
        public Nullable<decimal> RCT_AUTO_KEY { get; set; }
        public Nullable<decimal> CAP_AUTO_KEY { get; set; }
        public Nullable<decimal> CTH_AUTO_KEY { get; set; }
        public Nullable<decimal> CIM_AUTO_KEY { get; set; }
        public Nullable<decimal> CEM_AUTO_KEY { get; set; }
        public string CUSTOMS_DROP_SHIP { get; set; }
    
        public virtual AP_ACCOUNT AP_ACCOUNT { get; set; }
        public virtual ICollection<AP_DETAIL> AP_DETAIL { get; set; }
        public virtual COMPANy COMPANy { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual RO_CATEGORY_CODES RO_CATEGORY_CODES { get; set; }
        public virtual ICollection<RO_DETAIL> RO_DETAIL { get; set; }
        public virtual ICollection<RO_PRE_COSTING_CHARGES> RO_PRE_COSTING_CHARGES { get; set; }
        public virtual ICollection<SM_HEADER> SM_HEADER { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
        public virtual SYS_USERS SYS_USERS1 { get; set; }
        public virtual SYS_USERS SYS_USERS2 { get; set; }
    }
}
