//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RO_PRE_COSTING_CHARGES
    {
        public decimal RPG_AUTO_KEY { get; set; }
        public decimal ROH_AUTO_KEY { get; set; }
        public decimal PNM_AUTO_KEY { get; set; }
        public Nullable<decimal> EST_COST { get; set; }
        public string VENDOR_CHARGE_FLAG { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<System.DateTime> ENTRY_TIMESTAMP { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public Nullable<decimal> CHARGED_COST { get; set; }
        public string AIRWAY_BILL { get; set; }
        public Nullable<decimal> SVC_AUTO_KEY { get; set; }
        public Nullable<decimal> CUR_AUTO_KEY { get; set; }
        public Nullable<decimal> EST_PRICE { get; set; }
        public Nullable<decimal> CHARGED_PRICE { get; set; }
        public string INVOICE_NUMBER { get; set; }
        public string REMARKS { get; set; }
        public string NOTES { get; set; }
    
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER { get; set; }
        public virtual RO_HEADER RO_HEADER { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
