//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RO_SALES
    {
        public decimal ROS_AUTO_KEY { get; set; }
        public decimal SOD_AUTO_KEY { get; set; }
        public decimal ROD_AUTO_KEY { get; set; }
        public decimal QTY_ORDERED { get; set; }
        public decimal QTY_RECEIVED { get; set; }
    }
}
