//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RO_STATUS
    {
        public decimal RST_AUTO_KEY { get; set; }
        public string STATUS_CODE { get; set; }
        public string STATUS_TYPE { get; set; }
        public Nullable<decimal> SEQUENCE { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
