//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_DETAIL
    {
        public SM_DETAIL()
        {
            this.INVC_DETAIL = new HashSet<INVC_DETAIL>();
            this.PO_DETAIL1 = new HashSet<PO_DETAIL>();
            this.RC_DETAIL = new HashSet<RC_DETAIL>();
            this.SM_HISTORY = new HashSet<SM_HISTORY>();
            this.STOCKs = new HashSet<STOCK>();
            this.STOCK_RESERVATIONS = new HashSet<STOCK_RESERVATIONS>();
        }
    
        public decimal SMD_AUTO_KEY { get; set; }
        public decimal SMH_AUTO_KEY { get; set; }
        public decimal PNM_AUTO_KEY { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> SOD_AUTO_KEY { get; set; }
        public Nullable<decimal> QTY_RESERVED { get; set; }
        public Nullable<decimal> QTY_SHIPPED { get; set; }
        public Nullable<decimal> QTY_SHIP { get; set; }
        public Nullable<decimal> CUSTOMS_VALUE { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> ROD_AUTO_KEY { get; set; }
        public Nullable<decimal> RPP_AUTO_KEY { get; set; }
        public Nullable<decimal> POD_AUTO_KEY { get; set; }
        public string PACKAGE_OVERRIDE { get; set; }
        public string ROUTE_CODE { get; set; }
        public string ROUTE_DESC { get; set; }
        public string SDF_SMD_001 { get; set; }
        public string SDF_SMD_002 { get; set; }
        public string SDF_SMD_003 { get; set; }
        public string SDF_SMD_004 { get; set; }
        public string SDF_SMD_005 { get; set; }
        public string SDF_SMD_006 { get; set; }
        public string SDF_SMD_007 { get; set; }
        public string SDF_SMD_008 { get; set; }
        public string SDF_SMD_009 { get; set; }
        public string SDF_SMD_010 { get; set; }
        public Nullable<decimal> PPP_AUTO_KEY { get; set; }
        public string ECC { get; set; }
        public Nullable<decimal> WOB_AUTO_KEY { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> UNIT_COST { get; set; }
        public Nullable<decimal> CUSTOMER_PRICE { get; set; }
        public string CUST_REF { get; set; }
        public Nullable<decimal> SCC_AUTO_KEY { get; set; }
        public Nullable<decimal> STC_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<decimal> WCD_AUTO_KEY { get; set; }
    
        public virtual ICollection<INVC_DETAIL> INVC_DETAIL { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER { get; set; }
        public virtual PO_DETAIL PO_DETAIL { get; set; }
        public virtual ICollection<PO_DETAIL> PO_DETAIL1 { get; set; }
        public virtual ICollection<RC_DETAIL> RC_DETAIL { get; set; }
        public virtual RO_DETAIL RO_DETAIL { get; set; }
        public virtual RO_PIECE_PARTS RO_PIECE_PARTS { get; set; }
        public virtual SO_CATEGORY_CODES SO_CATEGORY_CODES { get; set; }
        public virtual ICollection<SM_HISTORY> SM_HISTORY { get; set; }
        public virtual ICollection<STOCK> STOCKs { get; set; }
        public virtual ICollection<STOCK_RESERVATIONS> STOCK_RESERVATIONS { get; set; }
        public virtual SM_HEADER SM_HEADER { get; set; }
        public virtual SO_DETAIL SO_DETAIL { get; set; }
        public virtual STOCK_CATEGORY_CODES STOCK_CATEGORY_CODES { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
