//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_CATEGORY_CODES
    {
        public SO_CATEGORY_CODES()
        {
            this.CQ_DETAIL = new HashSet<CQ_DETAIL>();
            this.INVC_DETAIL = new HashSet<INVC_DETAIL>();
            this.INVC_HEADER = new HashSet<INVC_HEADER>();
            this.SM_DETAIL = new HashSet<SM_DETAIL>();
            this.SO_DETAIL = new HashSet<SO_DETAIL>();
            this.SO_HEADER = new HashSet<SO_HEADER>();
        }
    
        public decimal SCC_AUTO_KEY { get; set; }
        public string SO_CATEGORY_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CANNOT_MODIFY { get; set; }
        public decimal SEQUENCE { get; set; }
        public Nullable<decimal> GLS_AUTO_KEY { get; set; }
        public string CONVERTED { get; set; }
        public string ROUTE_CODE { get; set; }
        public string ROUTE_DESC { get; set; }
        public string SDF_SCC_001 { get; set; }
        public string SDF_SCC_002 { get; set; }
        public string SDF_SCC_003 { get; set; }
        public string SDF_SCC_004 { get; set; }
        public string SDF_SCC_005 { get; set; }
        public string SDF_SCC_006 { get; set; }
        public string SDF_SCC_007 { get; set; }
        public string SDF_SCC_008 { get; set; }
        public string SDF_SCC_009 { get; set; }
        public string SDF_SCC_010 { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public string BRIDGE_REV { get; set; }
        public string BRIDGE_EXP { get; set; }
        public string HISTORICAL { get; set; }
    
        public virtual ICollection<CQ_DETAIL> CQ_DETAIL { get; set; }
        public virtual ICollection<INVC_DETAIL> INVC_DETAIL { get; set; }
        public virtual ICollection<INVC_HEADER> INVC_HEADER { get; set; }
        public virtual ICollection<SM_DETAIL> SM_DETAIL { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL { get; set; }
        public virtual ICollection<SO_HEADER> SO_HEADER { get; set; }
    }
}
