//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_DETAIL
    {
        public SO_DETAIL()
        {
            this.INVC_DETAIL = new HashSet<INVC_DETAIL>();
            this.RC_DETAIL = new HashSet<RC_DETAIL>();
            this.RO_DETAIL1 = new HashSet<RO_DETAIL>();
            this.SM_DETAIL = new HashSet<SM_DETAIL>();
            this.SO_DETAIL1 = new HashSet<SO_DETAIL>();
            this.STOCK_RESERVATIONS = new HashSet<STOCK_RESERVATIONS>();
        }
    
        public decimal SOD_AUTO_KEY { get; set; }
        public Nullable<decimal> CQD_AUTO_KEY { get; set; }
        public Nullable<decimal> PRI_AUTO_KEY { get; set; }
        public decimal PNM_AUTO_KEY { get; set; }
        public Nullable<decimal> PCC_AUTO_KEY { get; set; }
        public Nullable<decimal> UOM_AUTO_KEY { get; set; }
        public Nullable<decimal> CNC_AUTO_KEY { get; set; }
        public decimal SOH_AUTO_KEY { get; set; }
        public Nullable<decimal> SCC_AUTO_KEY { get; set; }
        public Nullable<decimal> ALT_PNM_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public string BUY_FLAG { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public decimal ITEM_NUMBER { get; set; }
        public Nullable<decimal> LIST_PRICE { get; set; }
        public Nullable<System.DateTime> NEXT_SHIP_DATE { get; set; }
        public string NOTES { get; set; }
        public string SELL_AS_TYPE { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> UNIT_COST { get; set; }
        public string WO_PRINT { get; set; }
        public Nullable<decimal> QTY_ORDERED { get; set; }
        public Nullable<decimal> QTY_PURCH { get; set; }
        public Nullable<decimal> QTY_PENDING_INVOICE { get; set; }
        public Nullable<decimal> QTY_INVOICED { get; set; }
        public Nullable<decimal> QTY_SHIP { get; set; }
        public Nullable<decimal> QTY_RESERVED { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string CLOSED_UPDATE { get; set; }
        public Nullable<decimal> LSH_AUTO_KEY { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public string CALC_TAX { get; set; }
        public Nullable<decimal> PERIOD_PRICE { get; set; }
        public Nullable<decimal> PBH_RATE { get; set; }
        public string BUY_OUT_FLAG { get; set; }
        public Nullable<decimal> SOD_PBH_SOURCE { get; set; }
        public Nullable<decimal> SPN_AUTO_KEY { get; set; }
        public Nullable<decimal> AGN_AUTO_KEY { get; set; }
        public string CUST_REF { get; set; }
        public Nullable<decimal> WOO_AUTO_KEY { get; set; }
        public string SOURCE_TABLE { get; set; }
        public Nullable<decimal> SOURCE_PK { get; set; }
        public Nullable<decimal> WOT_AUTO_KEY { get; set; }
        public string UPDATE_FROM_STR { get; set; }
        public string POD_LINK { get; set; }
        public string ROD_LINK { get; set; }
        public Nullable<decimal> REPAIR_STM { get; set; }
        public Nullable<decimal> EST_COST { get; set; }
        public Nullable<decimal> CUSTOMER_PRICE { get; set; }
        public Nullable<decimal> FOREIGN_LIST_PRICE { get; set; }
        public string RECEIVER_INSTR { get; set; }
        public string CONVERTED { get; set; }
        public Nullable<decimal> CMC_AUTO_KEY { get; set; }
        public Nullable<decimal> SPN_OVERRIDE { get; set; }
        public Nullable<decimal> CMC_OVERRIDE { get; set; }
        public Nullable<decimal> ROD_AUTO_KEY { get; set; }
        public Nullable<decimal> DSC_AUTO_KEY { get; set; }
        public Nullable<decimal> WHS_AUTO_KEY { get; set; }
        public Nullable<decimal> WOO_EXC_CHARGE { get; set; }
        public string PRINT_PICKTICKET_FLAG { get; set; }
        public Nullable<decimal> SYSUR_AUTH { get; set; }
        public string ROUTE_CODE { get; set; }
        public string ROUTE_DESC { get; set; }
        public Nullable<decimal> SPN_AUTO_KEY2 { get; set; }
        public Nullable<decimal> CMC_AUTO_KEY2 { get; set; }
        public Nullable<decimal> SPN_OVERRIDE2 { get; set; }
        public Nullable<decimal> CMC_OVERRIDE2 { get; set; }
        public Nullable<decimal> PDL_AUTO_KEY { get; set; }
        public Nullable<decimal> QTY_DELIVERED { get; set; }
        public string MANUAL_QTY_DELIV { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<decimal> ELC_AUTO_KEY { get; set; }
        public Nullable<decimal> CYCLE_RATE { get; set; }
        public Nullable<decimal> MIN_PBH_CHARGE { get; set; }
        public Nullable<decimal> MIN_CYCLE_CHARGE { get; set; }
        public Nullable<decimal> HOURS_DEPR { get; set; }
        public Nullable<decimal> CYCLES_DEPR { get; set; }
        public Nullable<decimal> STM_LEASE { get; set; }
        public Nullable<decimal> MKT_SOD { get; set; }
        public string SDF_SOD_001 { get; set; }
        public string SDF_SOD_002 { get; set; }
        public string SDF_SOD_003 { get; set; }
        public string SDF_SOD_004 { get; set; }
        public string SDF_SOD_005 { get; set; }
        public string SDF_SOD_006 { get; set; }
        public string SDF_SOD_007 { get; set; }
        public string SDF_SOD_008 { get; set; }
        public string SDF_SOD_009 { get; set; }
        public string SDF_SOD_010 { get; set; }
        public string SO_UDF_001 { get; set; }
        public string SO_UDF_002 { get; set; }
        public string SO_UDF_003 { get; set; }
        public string SO_UDF_004 { get; set; }
        public string SO_UDF_005 { get; set; }
        public Nullable<decimal> SHM_AUTO_KEY { get; set; }
        public string SO_UDF_006 { get; set; }
        public string SO_UDF_007 { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED { get; set; }
        public Nullable<decimal> SYSUR_MODIFIED { get; set; }
        public string PRINT_ACK_FLAG { get; set; }
        public Nullable<decimal> SUB_WOO { get; set; }
        public Nullable<decimal> OPM_AUTO_KEY { get; set; }
        public Nullable<decimal> WOB_AUTO_KEY { get; set; }
        public Nullable<decimal> COC_AUTO_KEY { get; set; }
        public Nullable<decimal> APC_AUTO_KEY { get; set; }
        public Nullable<decimal> RPP_AUTO_KEY { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public Nullable<decimal> RDX_AUTO_KEY { get; set; }
        public Nullable<decimal> CUST_PO_ITEM_NUM { get; set; }
        public string ECC { get; set; }
        public Nullable<decimal> CTH_AUTO_KEY { get; set; }
        public string SO_UDF_008 { get; set; }
        public Nullable<System.DateTime> CUST_REQ_DATE { get; set; }
        public string LEASE_DAILY_RATE_FLAG { get; set; }
        public string LEASE_AUTO_TIMELOG { get; set; }
        public string MIN_HOURS_COUNT_FLAG { get; set; }
        public string MIN_CYCLES_COUNT_FLAG { get; set; }
        public string LEASE_HOURS_OR_CYCLES { get; set; }
        public Nullable<decimal> PBH_AUTO_KEY { get; set; }
        public string LEASE_MIN_CHARGE_FLAG { get; set; }
        public Nullable<decimal> SPS_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> UDD_SOD_001 { get; set; }
        public Nullable<System.DateTime> UDD_SOD_002 { get; set; }
        public Nullable<decimal> SOD_PARENT { get; set; }
        public Nullable<decimal> ACT_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<decimal> STC_AUTO_KEY { get; set; }
        public Nullable<decimal> SO_UDN_001 { get; set; }
        public Nullable<decimal> SO_UDN_002 { get; set; }
        public Nullable<decimal> SO_UDN_003 { get; set; }
        public Nullable<decimal> SO_UDN_004 { get; set; }
        public Nullable<decimal> SO_UDN_005 { get; set; }
        public Nullable<decimal> SO_UDN_006 { get; set; }
        public Nullable<decimal> SO_UDN_007 { get; set; }
        public Nullable<decimal> SO_UDN_008 { get; set; }
        public Nullable<decimal> SO_UDN_009 { get; set; }
        public Nullable<decimal> SO_UDN_010 { get; set; }
        public Nullable<decimal> CIM_AUTO_KEY { get; set; }
        public Nullable<decimal> CEM_AUTO_KEY { get; set; }
        public Nullable<decimal> GROUP_NUMBER { get; set; }
    
        public virtual APPLICATION_CODES APPLICATION_CODES { get; set; }
        public virtual COMMISSION_CODES COMMISSION_CODES { get; set; }
        public virtual COMMISSION_CODES COMMISSION_CODES1 { get; set; }
        public virtual COMMISSION_CODES COMMISSION_CODES2 { get; set; }
        public virtual COMMISSION_CODES COMMISSION_CODES3 { get; set; }
        public virtual CQ_DETAIL CQ_DETAIL { get; set; }
        public virtual ICollection<INVC_DETAIL> INVC_DETAIL { get; set; }
        public virtual PART_CONDITION_CODES PART_CONDITION_CODES { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER1 { get; set; }
        public virtual ICollection<RC_DETAIL> RC_DETAIL { get; set; }
        public virtual RO_DETAIL RO_DETAIL { get; set; }
        public virtual ICollection<RO_DETAIL> RO_DETAIL1 { get; set; }
        public virtual RO_PIECE_PARTS RO_PIECE_PARTS { get; set; }
        public virtual ICollection<SM_DETAIL> SM_DETAIL { get; set; }
        public virtual SO_CATEGORY_CODES SO_CATEGORY_CODES { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL1 { get; set; }
        public virtual SO_DETAIL SO_DETAIL2 { get; set; }
        public virtual ICollection<STOCK_RESERVATIONS> STOCK_RESERVATIONS { get; set; }
        public virtual SO_HEADER SO_HEADER { get; set; }
        public virtual STOCK_CATEGORY_CODES STOCK_CATEGORY_CODES { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
