//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_HEADER
    {
        public SO_HEADER()
        {
            this.SM_HEADER = new HashSet<SM_HEADER>();
            this.SO_DETAIL = new HashSet<SO_DETAIL>();
        }
    
        public decimal SOH_AUTO_KEY { get; set; }
        public decimal CMP_AUTO_KEY { get; set; }
        public Nullable<decimal> AGN_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public Nullable<decimal> CUR_AUTO_KEY { get; set; }
        public Nullable<decimal> SVC_AUTO_KEY { get; set; }
        public string SO_NUMBER { get; set; }
        public Nullable<decimal> AGENT_COMM { get; set; }
        public string ATTENTION { get; set; }
        public string COMPANY_REF_NUMBER { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public string FAX_NUMBER { get; set; }
        public string HISTORICAL_FLAG { get; set; }
        public Nullable<System.DateTime> REC_DATE { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> NUMBER_OF_ITEMS { get; set; }
        public Nullable<decimal> TOTAL_COST { get; set; }
        public Nullable<decimal> TOTAL_PRICE { get; set; }
        public Nullable<decimal> INVOICEABLE { get; set; }
        public string OPEN_FLAG { get; set; }
        public string PHONE_NUMBER { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string CLOSED_UPDATE { get; set; }
        public Nullable<decimal> DPT_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSCM_AUTO_KEY { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public Nullable<decimal> TXT_AUTO_KEY { get; set; }
        public string TAX_METHOD { get; set; }
        public string BILL_ADDRESS1 { get; set; }
        public string BILL_ADDRESS2 { get; set; }
        public string BILL_ADDRESS3 { get; set; }
        public string BILL_ADDRESS4 { get; set; }
        public string BILL_ADDRESS5 { get; set; }
        public string SHIP_ADDRESS1 { get; set; }
        public string SHIP_ADDRESS2 { get; set; }
        public string SHIP_ADDRESS3 { get; set; }
        public string SHIP_ADDRESS4 { get; set; }
        public string SHIP_ADDRESS5 { get; set; }
        public Nullable<decimal> TMC_AUTO_KEY { get; set; }
        public Nullable<decimal> SPN_AUTO_KEY { get; set; }
        public Nullable<decimal> CST_AUTO_KEY { get; set; }
        public string BILL_NAME { get; set; }
        public string SHIP_NAME { get; set; }
        public string COMPLETE_SHIP { get; set; }
        public string CONVERTED { get; set; }
        public Nullable<decimal> GEO_AUTO_KEY { get; set; }
        public Nullable<decimal> ACT_AUTO_KEY { get; set; }
        public Nullable<decimal> SVA_AUTO_KEY { get; set; }
        public Nullable<decimal> CTH_AUTO_KEY { get; set; }
        public string FOB { get; set; }
        public Nullable<decimal> USR_AUTO_KEY { get; set; }
        public Nullable<decimal> MKT_SOH { get; set; }
        public string MKT_NOTES { get; set; }
        public string SDF_SOH_001 { get; set; }
        public string SDF_SOH_002 { get; set; }
        public string SDF_SOH_003 { get; set; }
        public string SDF_SOH_004 { get; set; }
        public string SDF_SOH_005 { get; set; }
        public string SDF_SOH_006 { get; set; }
        public string SDF_SOH_007 { get; set; }
        public string SDF_SOH_008 { get; set; }
        public string SDF_SOH_009 { get; set; }
        public string SDF_SOH_010 { get; set; }
        public Nullable<decimal> ELC_AUTO_KEY { get; set; }
        public string TRACK_CHANGES { get; set; }
        public Nullable<decimal> SCC_AUTO_KEY { get; set; }
        public Nullable<decimal> COC_AUTO_KEY { get; set; }
        public Nullable<decimal> DTC_AUTO_KEY { get; set; }
        public string AEX_FLAG { get; set; }
        public string UDF_SOH_001 { get; set; }
        public string UDF_SOH_002 { get; set; }
        public string UDF_SOH_003 { get; set; }
        public string UDF_SOH_004 { get; set; }
        public string UDF_SOH_005 { get; set; }
        public string SPEC_CIC { get; set; }
        public string SPEC_SPL { get; set; }
        public Nullable<decimal> SPEC_POC { get; set; }
        public Nullable<decimal> SPEC_BNO { get; set; }
        public Nullable<decimal> SPEC_QTL { get; set; }
        public Nullable<decimal> SPEC_EVT { get; set; }
        public string SPEC_SENDER { get; set; }
        public string SPEC_RECEIVER { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED { get; set; }
        public Nullable<decimal> SYSUR_MODIFIED { get; set; }
        public string BATCH_NUMBER { get; set; }
        public Nullable<decimal> MSG_AK_ACK { get; set; }
        public Nullable<System.DateTime> ACK_SENT { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string CUST_EDI_CODE { get; set; }
        public string INTERNAL_FLAG { get; set; }
        public Nullable<decimal> SHIP_PRIORITY { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public string EVENT_MGR { get; set; }
        public Nullable<decimal> SYSUR_EVENT_MGR { get; set; }
        public string RECO { get; set; }
        public Nullable<decimal> PAYMENT_AMT { get; set; }
        public string CHECK_NUMBER { get; set; }
        public Nullable<decimal> BNK_AUTO_KEY { get; set; }
        public Nullable<decimal> FOREIGN_PMT_AMT { get; set; }
        public Nullable<decimal> PMT_AUTO_KEY { get; set; }
        public Nullable<decimal> CCR_AUTO_KEY { get; set; }
        public string URL_LINK { get; set; }
        public Nullable<decimal> SYSUR_CQ_SUPERVISOR { get; set; }
        public Nullable<System.DateTime> EXP_DATE { get; set; }
        public string CC_CUSTOMER_NAME { get; set; }
        public string CC_STREET_ADDRESS { get; set; }
        public string CC_CITY_STATE_ZIP { get; set; }
        public Nullable<System.DateTime> UDD_SOH_001 { get; set; }
        public string SDF_SOH_011 { get; set; }
        public string SDF_SOH_012 { get; set; }
        public string SDF_SOH_013 { get; set; }
        public string SDF_SOH_014 { get; set; }
        public string SDF_SOH_015 { get; set; }
        public Nullable<decimal> SOS_AUTO_KEY { get; set; }
        public string EUC_CONFIRMED { get; set; }
        public string RELEASED_TO_SHIPPING { get; set; }
        public Nullable<decimal> UDN_SOH_001 { get; set; }
        public Nullable<decimal> UDN_SOH_002 { get; set; }
        public Nullable<decimal> UDN_SOH_003 { get; set; }
        public Nullable<decimal> UDN_SOH_004 { get; set; }
        public Nullable<decimal> UDN_SOH_005 { get; set; }
        public Nullable<decimal> UDN_SOH_006 { get; set; }
        public Nullable<decimal> UDN_SOH_007 { get; set; }
        public Nullable<decimal> UDN_SOH_008 { get; set; }
        public Nullable<decimal> UDN_SOH_009 { get; set; }
        public Nullable<decimal> UDN_SOH_010 { get; set; }
        public Nullable<decimal> CST_SOLD_TO { get; set; }
        public Nullable<decimal> CMP_DROP_SHIP { get; set; }
        public Nullable<decimal> CIM_AUTO_KEY { get; set; }
        public Nullable<decimal> CEM_AUTO_KEY { get; set; }
        public Nullable<decimal> CMP_FREIGHT_FORWARDER { get; set; }
        public Nullable<decimal> CST_FREIGHT_FORWARDER { get; set; }
        public Nullable<decimal> CMP_FOREIGN_CONSIGN { get; set; }
        public Nullable<decimal> CST_FOREIGN_CONSIGN { get; set; }
        public string CUSTOMS_DROP_SHIP { get; set; }
    
        public virtual AGENT AGENT { get; set; }
        public virtual COMPANy COMPANy { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<SM_HEADER> SM_HEADER { get; set; }
        public virtual SO_CATEGORY_CODES SO_CATEGORY_CODES { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL { get; set; }
        public virtual SO_STATUS SO_STATUS { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
        public virtual SYS_USERS SYS_USERS1 { get; set; }
        public virtual SYS_USERS SYS_USERS2 { get; set; }
    }
}
