//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_STATUS
    {
        public SO_STATUS()
        {
            this.SO_HEADER = new HashSet<SO_HEADER>();
        }
    
        public decimal SOS_AUTO_KEY { get; set; }
        public string STATUS_CODE { get; set; }
        public string STATUS_TYPE { get; set; }
        public Nullable<decimal> SEQUENCE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<SO_HEADER> SO_HEADER { get; set; }
    }
}
