//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_RESERVATIONS
    {
        public STOCK_RESERVATIONS()
        {
            this.RC_DETAIL = new HashSet<RC_DETAIL>();
            this.STOCKs = new HashSet<STOCK>();
        }
    
        public decimal STR_AUTO_KEY { get; set; }
        public Nullable<decimal> SOD_AUTO_KEY { get; set; }
        public decimal STM_AUTO_KEY { get; set; }
        public Nullable<decimal> ROD_AUTO_KEY { get; set; }
        public Nullable<decimal> CNC_AUTO_KEY { get; set; }
        public Nullable<decimal> IND_AUTO_KEY { get; set; }
        public Nullable<decimal> WOO_AUTO_KEY { get; set; }
        public Nullable<decimal> WOB_AUTO_KEY { get; set; }
        public Nullable<decimal> WTT_AUTO_KEY { get; set; }
        public Nullable<decimal> SMD_AUTO_KEY { get; set; }
        public Nullable<decimal> RPP_AUTO_KEY { get; set; }
        public Nullable<decimal> WCD_AUTO_KEY { get; set; }
        public Nullable<decimal> UNIT_COST { get; set; }
        public Nullable<decimal> QTY_RESERVED { get; set; }
        public Nullable<decimal> QTY_SHIP { get; set; }
        public Nullable<decimal> QTY_INVOICED { get; set; }
        public Nullable<decimal> QTY_REPAIRED { get; set; }
        public Nullable<decimal> QTY_SCRAPPED { get; set; }
        public Nullable<decimal> QTY_CREDIT { get; set; }
        public Nullable<decimal> QTY_NEW_SCRAP_LINE { get; set; }
        public Nullable<decimal> QTY_LEASED { get; set; }
        public Nullable<decimal> QTY_SHIPPED { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY_SCAN { get; set; }
        public Nullable<System.DateTime> DATE_SCAN { get; set; }
        public string CONVERTED { get; set; }
        public Nullable<decimal> POD_AUTO_KEY { get; set; }
        public string PRINT_PICK_TAG { get; set; }
        public Nullable<decimal> MXP_AUTO_KEY { get; set; }
        public Nullable<decimal> EBI_AUTO_KEY { get; set; }
        public string SDF_STR_001 { get; set; }
        public string SDF_STR_002 { get; set; }
        public string SDF_STR_003 { get; set; }
        public string SDF_STR_004 { get; set; }
        public string SDF_STR_005 { get; set; }
        public string SDF_STR_006 { get; set; }
        public string SDF_STR_007 { get; set; }
        public string SDF_STR_008 { get; set; }
        public string SDF_STR_009 { get; set; }
        public string SDF_STR_010 { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<decimal> PPP_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSUR_TOOL_ISSUED { get; set; }
        public string PRINTED { get; set; }
        public Nullable<decimal> STI_AUTO_KEY { get; set; }
        public Nullable<decimal> QTY_ISSUED { get; set; }
        public Nullable<decimal> QTY_UNDO_ISSUE { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public string PRINT_CERT_FLAG { get; set; }
        public Nullable<decimal> CRQ_AUTO_KEY { get; set; }
        public Nullable<decimal> PICK_ID { get; set; }
        public Nullable<System.DateTime> DATE_PRINTED { get; set; }
        public Nullable<decimal> RESERVATION_ID { get; set; }
        public Nullable<System.DateTime> PKG_SCANNED_DATE { get; set; }
        public Nullable<decimal> PKG_QTY_SCANNED { get; set; }
    
        public virtual INVC_DETAIL INVC_DETAIL { get; set; }
        public virtual PO_DETAIL PO_DETAIL { get; set; }
        public virtual ICollection<RC_DETAIL> RC_DETAIL { get; set; }
        public virtual RO_DETAIL RO_DETAIL { get; set; }
        public virtual RO_PIECE_PARTS RO_PIECE_PARTS { get; set; }
        public virtual SM_DETAIL SM_DETAIL { get; set; }
        public virtual SO_DETAIL SO_DETAIL { get; set; }
        public virtual STOCK STOCK { get; set; }
        public virtual ICollection<STOCK> STOCKs { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
        public virtual SYS_USERS SYS_USERS1 { get; set; }
    }
}
