//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public STOCK()
        {
            this.CQ_DETAIL = new HashSet<CQ_DETAIL>();
            this.PO_DETAIL3 = new HashSet<PO_DETAIL>();
            this.SM_HISTORY = new HashSet<SM_HISTORY>();
            this.STOCK_RESERVATIONS = new HashSet<STOCK_RESERVATIONS>();
            this.STOCK1 = new HashSet<STOCK>();
        }
    
        public decimal STM_AUTO_KEY { get; set; }
        public Nullable<decimal> STR_AUTO_KEY { get; set; }
        public decimal PNM_AUTO_KEY { get; set; }
        public Nullable<decimal> CMP_AUTO_KEY { get; set; }
        public Nullable<decimal> POD_AUTO_KEY { get; set; }
        public Nullable<decimal> PCC_AUTO_KEY { get; set; }
        public Nullable<decimal> IFC_AUTO_KEY { get; set; }
        public Nullable<decimal> LOC_AUTO_KEY { get; set; }
        public Nullable<decimal> WHS_AUTO_KEY { get; set; }
        public Nullable<decimal> CNC_AUTO_KEY { get; set; }
        public Nullable<decimal> CTS_AUTO_KEY { get; set; }
        public Nullable<decimal> SYSUR_AUTO_KEY { get; set; }
        public decimal STOCK_LINE { get; set; }
        public string HISTORICAL_FLAG { get; set; }
        public decimal CTRL_NUMBER { get; set; }
        public decimal CTRL_ID { get; set; }
        public Nullable<decimal> CORE_VALUE { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public Nullable<System.DateTime> EXP_DATE { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> OVHL_COST { get; set; }
        public string OWNER { get; set; }
        public string ORIGINAL_PO_NUMBER { get; set; }
        public string PART_CERT_NUMBER { get; set; }
        public Nullable<System.DateTime> REC_DATE { get; set; }
        public string RECEIVER_NUMBER { get; set; }
        public string REMARKS { get; set; }
        public string RO_INFO { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string SHELF_LIFE { get; set; }
        public Nullable<System.DateTime> SOLD_DATE { get; set; }
        public string SO_INVC_NUMBER { get; set; }
        public string TAGGED_BY { get; set; }
        public Nullable<System.DateTime> TAG_DATE { get; set; }
        public Nullable<decimal> UNIT_COST { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string VENDOR_INVC_NUMBER { get; set; }
        public string IC_UDF_005 { get; set; }
        public string IC_UDF_006 { get; set; }
        public string IC_UDF_007 { get; set; }
        public string IC_UDF_008 { get; set; }
        public string IC_UDF_009 { get; set; }
        public string IC_UDF_010 { get; set; }
        public Nullable<decimal> QTY_OH { get; set; }
        public Nullable<decimal> QTY_REC { get; set; }
        public Nullable<decimal> QTY_INVOICED { get; set; }
        public Nullable<decimal> QTY_ADJ { get; set; }
        public Nullable<decimal> QTY_RESERVED { get; set; }
        public Nullable<decimal> QTY_AVAILABLE { get; set; }
        public Nullable<decimal> QTY_REPAIRED { get; set; }
        public Nullable<decimal> QTY_SCRAPPED { get; set; }
        public Nullable<decimal> ADJ_COST { get; set; }
        public Nullable<decimal> REC_COST { get; set; }
        public Nullable<decimal> IND_AUTO_KEY { get; set; }
        public Nullable<decimal> QTY_CREDIT { get; set; }
        public Nullable<decimal> STM_ORIGINAL { get; set; }
        public string DESCRIPTION { get; set; }
        public string CLOSED_UPDATE { get; set; }
        public string DESCRIPTION_UPPER { get; set; }
        public Nullable<System.DateTime> QTY_CHANGE_DATE { get; set; }
        public Nullable<decimal> VENDOR_PRICE { get; set; }
        public Nullable<decimal> SYSCM_AUTO_KEY { get; set; }
        public Nullable<decimal> GLA_AUTO_KEY { get; set; }
        public Nullable<decimal> APD_AUTO_KEY { get; set; }
        public string IQ_ENABLE { get; set; }
        public string HOLD_LINE { get; set; }
        public Nullable<decimal> RRD_AUTO_KEY { get; set; }
        public Nullable<decimal> STM_TRANSFER { get; set; }
        public Nullable<decimal> LSH_AUTO_KEY { get; set; }
        public Nullable<decimal> PBH_ACCUMULATIVE { get; set; }
        public string TAIL_NUMBER { get; set; }
        public string PN { get; set; }
        public string PN_UPPER { get; set; }
        public Nullable<decimal> REC_TRAN_ID { get; set; }
        public string CUSTOMER_OWNED { get; set; }
        public Nullable<decimal> STC_AUTO_KEY { get; set; }
        public string PART_MERGE { get; set; }
        public Nullable<decimal> SMD_AUTO_KEY { get; set; }
        public Nullable<decimal> LOC_ORIGINAL { get; set; }
        public Nullable<decimal> WHS_ORIGINAL { get; set; }
        public string SPLIT { get; set; }
        public Nullable<decimal> SERIES_NUMBER { get; set; }
        public Nullable<decimal> SERIES_ID { get; set; }
        public string CONVERTED { get; set; }
        public Nullable<decimal> ROD_AUTO_KEY { get; set; }
        public Nullable<decimal> RCD_AUTO_KEY { get; set; }
        public Nullable<decimal> RCL_AUTO_KEY { get; set; }
        public string REJECTED_LINE { get; set; }
        public Nullable<System.DateTime> CHANGE_TIMESTAMP { get; set; }
        public Nullable<decimal> STM_LOT { get; set; }
        public string WO_CREATED { get; set; }
        public string STOCK_AUDIT { get; set; }
        public Nullable<decimal> GLA_OLD { get; set; }
        public string OFF_WING { get; set; }
        public Nullable<decimal> WPT_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> ORDER_REC_DATE { get; set; }
        public Nullable<decimal> DPT_AUTO_KEY { get; set; }
        public string VISIBLE_MKT { get; set; }
        public string LOT_APL_RO_COST { get; set; }
        public string LOT_ALW_PRECOST { get; set; }
        public string LOT_COST_DELAYED { get; set; }
        public string PRINT_MO_CERT { get; set; }
        public Nullable<decimal> PARTS_COST { get; set; }
        public Nullable<decimal> LABOR_COST { get; set; }
        public Nullable<decimal> VO_COST { get; set; }
        public Nullable<decimal> FO_COST { get; set; }
        public Nullable<decimal> OSV_COST { get; set; }
        public string FIXED_UNIT_COST { get; set; }
        public Nullable<decimal> WOO_MFG { get; set; }
        public Nullable<decimal> EBT_AUTO_KEY { get; set; }
        public Nullable<decimal> SMC_AUTO_KEY { get; set; }
        public string SMC_CODE { get; set; }
        public Nullable<decimal> UNIT_FREIGHT_COST { get; set; }
        public Nullable<decimal> POD_FREIGHT { get; set; }
        public string NO_LOT_IMAGES { get; set; }
        public string TAG_NUMBER { get; set; }
        public Nullable<System.DateTime> MFG_DATE { get; set; }
        public string HAS_WARRANTY { get; set; }
        public Nullable<decimal> WARRANTY_LENGTH { get; set; }
        public Nullable<System.DateTime> WARRANTY_EXPR_DATE { get; set; }
        public string VEHICLE_NUMBER { get; set; }
        public string LICENSE_NUMBER { get; set; }
        public Nullable<decimal> INC_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> INSURANCE_EXPR_DATE { get; set; }
        public Nullable<System.DateTime> REG_EXPR_DATE { get; set; }
        public Nullable<System.DateTime> SERVICE_START_DATE { get; set; }
        public Nullable<decimal> UNIT_DEPR_BASIS { get; set; }
        public Nullable<System.DateTime> DISPOSED_DATE { get; set; }
        public Nullable<decimal> DPM_AUTO_KEY { get; set; }
        public Nullable<decimal> USEFUL_LIFE { get; set; }
        public Nullable<decimal> DEPR_AMOUNT { get; set; }
        public string TRACK_CHANGES { get; set; }
        public string REVISION { get; set; }
        public Nullable<decimal> POP_AUTO_KEY { get; set; }
        public Nullable<decimal> MKT_PRICE { get; set; }
        public string SDF_STM_001 { get; set; }
        public string SDF_STM_002 { get; set; }
        public string SDF_STM_003 { get; set; }
        public string SDF_STM_004 { get; set; }
        public string SDF_STM_005 { get; set; }
        public string SDF_STM_006 { get; set; }
        public string SDF_STM_007 { get; set; }
        public string SDF_STM_008 { get; set; }
        public string SDF_STM_009 { get; set; }
        public string SDF_STM_010 { get; set; }
        public Nullable<decimal> MISC_COST { get; set; }
        public Nullable<System.DateTime> INSPECT_DUE_DATE { get; set; }
        public string HOLOGRAM_NUMBER { get; set; }
        public Nullable<decimal> ORIG_STOCK_VAL { get; set; }
        public Nullable<System.DateTime> CALIBRATION_DATE { get; set; }
        public Nullable<System.DateTime> DATE_CHECK_IN { get; set; }
        public Nullable<System.DateTime> DATE_CHECK_OUT { get; set; }
        public string CALIB_REMARKS { get; set; }
        public string CALIB_DOC { get; set; }
        public string CALIB_REF_MASTER { get; set; }
        public string CALIB_REF_INSTR { get; set; }
        public Nullable<decimal> CMP_CALIB_BY { get; set; }
        public string TOOL_STATUS { get; set; }
        public string MANUALLY_ADDED { get; set; }
        public Nullable<System.DateTime> LOC_VALIDATED { get; set; }
        public Nullable<decimal> QTY_REC_UC { get; set; }
        public Nullable<decimal> REC_COST_UC { get; set; }
        public string UOM_CONVERTED { get; set; }
        public string AIRWAY_BILL { get; set; }
        public string HOLDING_FILE { get; set; }
        public Nullable<decimal> MSR_AUTO_KEY { get; set; }
        public string ALT_ID { get; set; }
        public Nullable<decimal> IC_UDN_001 { get; set; }
        public Nullable<decimal> IC_UDN_002 { get; set; }
        public Nullable<decimal> IC_UDN_003 { get; set; }
        public Nullable<decimal> IC_UDN_004 { get; set; }
        public Nullable<decimal> IC_UDN_005 { get; set; }
        public Nullable<decimal> IC_UDN_006 { get; set; }
        public Nullable<decimal> IC_UDN_007 { get; set; }
        public Nullable<decimal> IC_UDN_008 { get; set; }
        public Nullable<decimal> IC_UDN_009 { get; set; }
        public Nullable<decimal> IC_UDN_010 { get; set; }
        public string MFG_LOT_NUM { get; set; }
        public Nullable<decimal> MKT_LIST_PRICE { get; set; }
        public string MFG_OSP { get; set; }
        public string TURNIN_REC { get; set; }
        public Nullable<decimal> FAI_AUTO_KEY { get; set; }
        public string IC_UDF_020 { get; set; }
        public Nullable<System.DateTime> IC_UDF_021 { get; set; }
        public Nullable<System.DateTime> IC_UDF_022 { get; set; }
        public Nullable<decimal> CORE_COST { get; set; }
        public Nullable<decimal> OVHL_COST_CURRENT { get; set; }
        public Nullable<decimal> MOI_SCRAP { get; set; }
        public string REASON_FOR_HOLD { get; set; }
        public Nullable<decimal> CONVERSION_ID { get; set; }
        public Nullable<System.DateTime> LAST_OVERHAUL_DATE { get; set; }
        public Nullable<decimal> LIQUIDATE_OPTION { get; set; }
        public string LOT_SCRAPPED { get; set; }
        public Nullable<decimal> MOI_NC { get; set; }
        public string NC { get; set; }
        public Nullable<decimal> NC_CMP_VENDOR { get; set; }
        public Nullable<decimal> UNREC_EXP { get; set; }
        public string VERIFY_FLAG { get; set; }
        public Nullable<decimal> MARKUP_AMT { get; set; }
        public Nullable<decimal> POD_FROM_LOT { get; set; }
        public Nullable<decimal> QTY_REC_FROM_LOT { get; set; }
        public Nullable<decimal> REC_COST_FROM_LOT { get; set; }
        public string BRIDGE_REFERENCE { get; set; }
        public string RO_TYPE { get; set; }
        public Nullable<decimal> CUSTOMS_STATUS { get; set; }
        public string INCIDENT_RELATED_FLAG { get; set; }
        public string INCIDENT_RELATED_NOTES { get; set; }
        public Nullable<decimal> ORIGINAL_POC { get; set; }
        public Nullable<decimal> ORIGINAL_COST { get; set; }
        public Nullable<decimal> EIT_AUTO_KEY { get; set; }
        public Nullable<decimal> TTP_AUTO_KEY { get; set; }
        public Nullable<System.DateTime> HISTORICAL_TIMESTAMP { get; set; }
        public string CAAC_FLAG { get; set; }
        public string WRITE_DOWN_REF { get; set; }
        public Nullable<System.DateTime> LAST_WRITE_DOWN { get; set; }
        public Nullable<decimal> POS_REF { get; set; }
        public string IC_UDF_023 { get; set; }
        public Nullable<decimal> IC_UDL_001 { get; set; }
        public Nullable<decimal> IC_UDL_002 { get; set; }
        public Nullable<decimal> IC_UDL_003 { get; set; }
        public Nullable<decimal> IC_UDL_004 { get; set; }
        public Nullable<decimal> IC_UDL_005 { get; set; }
        public string IC_UDL_005_TXT { get; set; }
        public Nullable<decimal> CSS_AUTO_KEY { get; set; }
        public string WRITE_DOWN_SPLIT { get; set; }
        public string MC_BUY_OUT { get; set; }
        public Nullable<System.DateTime> DATE_FIRST_OPENED { get; set; }
        public Nullable<decimal> CIM_AUTO_KEY { get; set; }
        public Nullable<decimal> CEM_AUTO_KEY { get; set; }
        public string SCRAP_REMARKS { get; set; }
        public Nullable<decimal> SCR_AUTO_KEY { get; set; }
    
        public virtual COMPANy COMPANy { get; set; }
        public virtual COMPANy COMPANy1 { get; set; }
        public virtual COMPANy COMPANy2 { get; set; }
        public virtual ICollection<CQ_DETAIL> CQ_DETAIL { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual PART_CONDITION_CODES PART_CONDITION_CODES { get; set; }
        public virtual PARTS_MASTER PARTS_MASTER { get; set; }
        public virtual PO_CATEGORY_CODES PO_CATEGORY_CODES { get; set; }
        public virtual PO_DETAIL PO_DETAIL { get; set; }
        public virtual PO_DETAIL PO_DETAIL1 { get; set; }
        public virtual PO_DETAIL PO_DETAIL2 { get; set; }
        public virtual ICollection<PO_DETAIL> PO_DETAIL3 { get; set; }
        public virtual RC_DETAIL RC_DETAIL { get; set; }
        public virtual RO_DETAIL RO_DETAIL { get; set; }
        public virtual SM_DETAIL SM_DETAIL { get; set; }
        public virtual ICollection<SM_HISTORY> SM_HISTORY { get; set; }
        public virtual STOCK_CATEGORY_CODES STOCK_CATEGORY_CODES { get; set; }
        public virtual ICollection<STOCK_RESERVATIONS> STOCK_RESERVATIONS { get; set; }
        public virtual ICollection<STOCK> STOCK1 { get; set; }
        public virtual STOCK STOCK2 { get; set; }
        public virtual STOCK_RESERVATIONS STOCK_RESERVATIONS1 { get; set; }
        public virtual SYS_USERS SYS_USERS { get; set; }
    }
}
