//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuntumDB.QuantumModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_CATEGORY_CODES
    {
        public STOCK_CATEGORY_CODES()
        {
            this.INVC_DETAIL = new HashSet<INVC_DETAIL>();
            this.PARTS_MASTER = new HashSet<PARTS_MASTER>();
            this.PO_DETAIL = new HashSet<PO_DETAIL>();
            this.PO_HEADER = new HashSet<PO_HEADER>();
            this.RO_DETAIL = new HashSet<RO_DETAIL>();
            this.SM_DETAIL = new HashSet<SM_DETAIL>();
            this.SO_DETAIL = new HashSet<SO_DETAIL>();
            this.STOCKs = new HashSet<STOCK>();
        }
    
        public decimal STC_AUTO_KEY { get; set; }
        public string STOCK_CATEGORY_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> GLS_AUTO_KEY { get; set; }
        public string CANNOT_MODIFY { get; set; }
        public decimal SEQUENCE { get; set; }
        public string EXCHANGE_ONLY { get; set; }
        public string SDF_STC_001 { get; set; }
        public string SDF_STC_002 { get; set; }
        public string SDF_STC_003 { get; set; }
        public string SDF_STC_004 { get; set; }
        public string SDF_STC_005 { get; set; }
        public string SDF_STC_006 { get; set; }
        public string SDF_STC_007 { get; set; }
        public string SDF_STC_008 { get; set; }
        public string SDF_STC_009 { get; set; }
        public string SDF_STC_010 { get; set; }
        public string VISIBLE_PORTAL { get; set; }
    
        public virtual ICollection<INVC_DETAIL> INVC_DETAIL { get; set; }
        public virtual ICollection<PARTS_MASTER> PARTS_MASTER { get; set; }
        public virtual ICollection<PO_DETAIL> PO_DETAIL { get; set; }
        public virtual ICollection<PO_HEADER> PO_HEADER { get; set; }
        public virtual ICollection<RO_DETAIL> RO_DETAIL { get; set; }
        public virtual ICollection<SM_DETAIL> SM_DETAIL { get; set; }
        public virtual ICollection<SO_DETAIL> SO_DETAIL { get; set; }
        public virtual ICollection<STOCK> STOCKs { get; set; }
    }
}
