SELECT "AGING","RO_DATE","RO_NUMBER","COMPANY_NAME","PN","SO_NUMBER",
"SO_CUSTOMER","USER_NAME","CONTACT","STATUS_CODE",
"SM_NUMBER","SHIP_DATE","DAYS_OUT","DAYS_SINCE_SHIPPED" 
FROM (
SELECT 
ROUND((SYSDATE)-ROH.ENTRY_DATE) AGING,

  ROH.ENTRY_DATE RO_DATE,
  ROH.RO_NUMBER,
  CMP.COMPANY_NAME,
 

 -- ROD.NEXT_DELIVERY_DATE,
  PNM.PN,
  SOH.SO_NUMBER, 
  SO_CMP.COMPANY_NAME SO_CUSTOMER,
  SU.user_name,
  pjh.prj_number AS Contact,
  pjs.status_code,
   SMH.SM_NUMBER,
  SMH.SHIP_DATE,

ROUND((SYSDATE)-SMH.SHIP_DATE) DAYS_OUT,

CASE 
WHEN ROUND((SYSDATE)-SMH.SHIP_DATE)>=0  AND ROUND((SYSDATE)-SMH.SHIP_DATE)<=29 THEN 'UNDER 30 DAYS'
WHEN ROUND((SYSDATE)-SMH.SHIP_DATE)>=30 AND ROUND((SYSDATE)-SMH.SHIP_DATE)<=60 THEN '30-60 DAYS'
WHEN ROUND((SYSDATE)-SMH.SHIP_DATE)>=61 AND ROUND((SYSDATE)-SMH.SHIP_DATE)<=90 THEN '60-90 DAYS'
WHEN ROUND((SYSDATE)-SMH.SHIP_DATE)>=91  THEN '90+ DAYS'
END AS DAYS_SINCE_SHIPPED
FROM RO_DETAIL ROD,
  RO_HEADER ROH,
  COMPANIES CMP,
  PARTS_MASTER PNM,
  PART_CONDITION_CODES PCC,
  CURRENCY CUR,
  STOCK_RESERVATIONS STR,
  STOCK STM,
  SO_DETAIL SOD, 
  SO_HEADER SOH,
  COMPANIES SO_CMP,
  project_header pjh,
  project_status pjs,
  project_links pjl,
  SYS_USERS SU,
  SM_DETAIL SMD, 
  SM_HEADER SMH
WHERE ROH.ROH_AUTO_KEY   = ROD.ROH_AUTO_KEY
AND CMP.CMP_AUTO_KEY     = ROH.CMP_AUTO_KEY
AND PNM.PNM_AUTO_KEY (+) = ROD.PNM_MODIFY
AND PCC.PCC_AUTO_KEY (+) = ROD.PCC_AUTO_KEY
AND CUR.CUR_AUTO_KEY (+) = ROH.CUR_AUTO_KEY
AND STR.ROD_AUTO_KEY (+) = ROD.ROD_AUTO_KEY
AND STM.STM_AUTO_KEY (+) = STR.STM_AUTO_KEY
AND SOD.SOD_AUTO_KEY(+)=ROD.SOD_AUTO_KEY
AND SOH.SOH_AUTO_KEY(+)=SOD.SOH_AUTO_KEY
AND SO_CMP.CMP_AUTO_KEY(+)=SOH.CMP_AUTO_KEY
AND SU.SYSUR_AUTO_KEY(+)=PJH.SYSUR_AUTO_KEY
and PJL.KEY_VALUE(+)= ROD.ROD_AUTO_KEY
AND PJH.PJH_AUTO_KEY(+)=PJL.PJH_AUTO_KEY
AND PJS.PJS_AUTO_KEY(+)=PJH.PJS_AUTO_KEY
AND SMD.ROD_AUTO_KEY(+)=ROD.ROD_AUTO_KEY
AND SMH.SMH_AUTO_KEY(+)=SMD.SMH_AUTO_KEY
AND PJH.PJM_AUTO_KEY(+)=8

AND roh.open_flag        ='T'
order by roh.entry_Date asc
)